### ISSUE TITLE
No synchronous `afterTests` anymore

### ISSUE THREAD

**Issue by wagenet** [testem/testem#1002]
The README implies that you can do a synchronous `afterTests`. However, I'm not seeing how this would work from the code. It's expected that you call the callback passed into your `afterTests` function. It used to work for me in the past, but I'm not actually seeing how it did now that I look at the code!

**Comment by johanneswuerbach** [comment]
`afterTests` was intended for async usage only https://github.com/testem/testem/pull/823.

You can still hook into the previously documented `Testem.on('all-test-results', function(results) {})` hook for synchronous usage.

May I ask what your use-case is and why you need a sync hook?

**Comment by wagenet** [comment]
@johanneswuerbach I don't have any specific need for it. However, my tests were set up without calling the `callback` this used to work and no longer works, leading to the tests just hanging. I've made a PR to update the README: https://github.com/testem/testem/pull/1003
