### ISSUE TITLE
Put failed tests at the top

### ISSUE THREAD

**Issue by stephenh** [testem/testem#1055]
Currently if I run ~1000+ testem tests, and I have 4 failures, I have to just scroll through the browser UI hunting for the failures.

Ideally the failed tests would be obvious to find; e.g. a cheap way would be to add a constant to search for, e.g. "FAILED", or even better would be to separate files that passed vs. files that had failures into two separate sections, instead of just listing them in order they were run in.

**Comment by johanneswuerbach** [comment]
Could you post your testem config and share which test framework you are using? Testem doesn't really provide a browser UI

**Comment by stephenh** [comment]
Hey, thanks for the quick response.

My testem config has a lot of odd/internal stuff in it, but the UI I was talking about looks like (just a snippet of the test count/progress box):

![image](https://cloud.githubusercontent.com/assets/6401/21869417/2c9a54ca-d81d-11e6-92df-51fd210429c6.png)

We use mocha+chai for test/asserts, and phantomjs for the ci build, and technically do have a custom test page, but it doesn't do anything too special.

Although now that I look closely, the test page is pulling in `mocha.css` and `mocha.js`, then calls `mocha.setup(bdd)`...

And I see what you mean, it's actually mocha that is doing all the rendering.

Thanks! I'll go bother them. :-)
