### ISSUE TITLE
src_files - do not allow duplicates

### ISSUE THREAD

**Issue by bradleylandis** [testem/testem#1067]
Currently, if you specify a file at the top of the list and then it matches a glob later in the list, the file is output into the SpecRunner.html twice.

To help with the problem of "order matters" when specifying source files, it would be great if when a glob is specified, if the matching file was already specified (explicitly or through another glob) then the current glob ignored it.  This would allow us to continue using the glob and just "pull up" those where the order matter.  

For reference, this is how karma works:
http://karma-runner.github.io/1.0/config/files.html

Ordering
The order of patterns determines the order in which files are included in the browser.
Multiple files matching a single pattern are sorted alphabetically.
Each file is included exactly once. If multiple patterns match the same file, it's included as if it only matched the first pattern.

**Comment by johanneswuerbach** [comment]
Sounds like a good addition, PRs are always welcome :-)

**Comment by bradleylandis** [comment]
https://github.com/testem/testem/pull/1109/files

I'd also suggest mocking out glob() for the tests so that changing files in the project doesn't cause tests to start failing.  I'd be happy to take a crack at that as well if your are interested.
