### ISSUE TITLE
Configure container dimensions?

### ISSUE THREAD

**Issue by tiandavis** [testem/testem#1082]
Hi Folks!

I know we can "Hide container" as an option:
![image](https://cloud.githubusercontent.com/assets/376230/23759677/73646ccc-04bb-11e7-87c2-fdb1a4abebb6.png)

But curious to know is there a way to configure container dimensions or increase the container size somehow - Maybe in testem.js(on) file? Reason I ask is our container is showing a bit small atm.
![image](https://cloud.githubusercontent.com/assets/376230/23772691/efc7c330-04e9-11e7-9a36-e3fcaadab9b9.png)

Here's our current testem.js file:

```
/*jshint node:true*/
module.exports = {
  "framework": "qunit",
  "test_page": "tests/index.html?hidepassed",
  "disable_watching": true,
  "launch_in_ci": [
    "PhantomJS"
  ],
  "launch_in_dev": [
    "PhantomJS",
    "Chrome"
  ]
};
```

Thanks Everyone!

EDIT:
To clarify, our goal would be to get to something closer to "full screen" maybe:
![image](https://cloud.githubusercontent.com/assets/376230/23771799/9841dad6-04e6-11e7-903e-0f2de85a497b.png)

**Comment by johanneswuerbach** [comment]
It looks like you are using ember-cli, would you mind opening an issue there if this is the case? Testem has no influence on how the test page might look like

**Comment by tiandavis** [comment]
Correct and Agreed. Thanks @johanneswuerbach!
