### ISSUE TITLE
Latest Firefox (52) -  Error: Browser failed to connect within 30s. testem.js not loaded?

### ISSUE THREAD

**Issue by limonte** [testem/testem#1084]
Testem works fine for my open-source project with Firefox 51: 

 - build: https://travis-ci.org/limonte/sweetalert2/builds/210064726
 - configuration: https://github.com/limonte/sweetalert2/blob/master/.travis.yml#L11

But if I set Firefox version to latest (current latest is 52), then it trows the exception: 

```
message: >
            Error: Browser failed to connect within 30s. testem.js not loaded?
            Stderr: 
             ExceptionHandler::GenerateDump cloned child 3309
            ExceptionHandler::SendContinueSignalToChild sent continue signal to child
            ExceptionHandler::WaitForContinueSignal waiting for continue signal...
```

 - build: https://travis-ci.org/limonte/sweetalert2/builds/210216981
 - configuration: https://github.com/limonte/sweetalert2/blob/testem-firefox/.travis.yml

**Comment by johanneswuerbach** [comment]
Do you see the same locally?

**Comment by limonte** [comment]
Seems that Firefox fixed the issue :rocket:
