### ISSUE TITLE
Support for chrome --headless

### ISSUE THREAD

**Issue by jboler** [testem/testem#1106]
As of version 57 Google Chrome can run headless. [Chromium has been able to for a while too](https://chromium.googlesource.com/chromium/src/+/lkgr/headless/README.md).

I'm using Testem 1.15.0 on Ubuntu 16.04 with an ember 2.11 project.

When I run `ember test` I can see via `ps aux` that Testem started running the tests with the right args but it still boots up a full desktop browser window:
```
/opt/google/chrome/chrome --headless --disable-gpu --user-data-dir=/tmp/testem-3394 --no-default-browser-check --no-first-run --ignore-certificate-errors --test-type --disable-renderer-backgrounding --disable-background-timer-throttling http://localhost:7357/3394/tests/index.html?hidepassed
```
When I start `/opt/google/chrome/chrome --headless --disable-gpu...` manually or with another test framework like Watir then it works headless.

My testem.js looks like this:
```
module.exports = {
  "framework": "qunit",
  "test_page": "tests/index.html?hidepassed",
  "disable_watching": true,
  "launch_in_ci": [
    "Chrome"
  ],
  "launch_in_dev": [
    "Chrome"
  ],
  "browser_args": {
    "Chrome": [
      "--headless --disable-gpu"
    ]
  }
};
```

**Comment by cibernox** [comment]
I've also tried to run chrome headless with no luck. It seems to be starting but it breaks. I'm not even sure if testem has anything to do, since it seems to break because of some audio problem.

FWIW, the project is open source so if anyone wants to peek, this is it: https://github.com/cibernox/ember-basic-dropdown/pull/256

**Comment by johanneswuerbach** [comment]
Looks like you have a small issue in your testem config @jboler, could you try splitting the args into multiple array elements?

```
"browser_args": {
    "Chrome": [
      "--headless","
      "--disable-gpu"
    ]
  }
```

**Comment by johanneswuerbach** [comment]
@cibernox sounds like you are hit by https://bugs.chromium.org/p/chromium/issues/detail?id=678948

**Comment by cibernox** [comment]
@johanneswuerbach Good catch. Seems that it was fixed the 17th of January, so it should be in the dev channel by now. Perhaps even in beta. I'll try to update.

**Comment by jboler** [comment]
@johanneswuerbach With that configuration I get:
```
not ok 1 Chrome - error
    ---
        message: >
            Error: Browser exited unexpectedly
            
        Log: |
            { type: 'error', text: 'Error: Browser exited unexpectedly' }
```
Looking at `ps aux`,  the command being run is the same as when I put those 2 flags in 1 string.

**Comment by jboler** [comment]
There's also this process that doesn't have the `--headless` flag. Maybe it should have it?

```
/opt/google/chrome/chrome --disable-background-networking --disable-background-timer-throttling --disable-client-side-phishing-detection --disable-default-apps --disable-gpu --disable-hang-monitor --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --disable-web-resources --enable-automation --enable-logging --headless --ignore-certificate-errors --load-extension=/tmp/.org.chromium.Chromium.gBMvz5/internal --log-level=0 --metrics-recording-only --no-default-browser-check --no-first-run --password-store=basic --remote-debugging-port=12389 --safebrowsing-disable-auto-update --test-type=webdriver --use-mock-keychain --user-data-dir=/tmp/.org.chromium.Chromium.w8KZaX data:,
```

**Comment by johanneswuerbach** [comment]
What happens when you run test in interactive mode `ember test --serve`? Is headless chrome starting this way?

**Comment by cibernox** [comment]
@johanneswuerbach I think I can answer for @jboler since I have the same error.

Yes, the error is the same with `ember test` and with `ember test --serve`.
The error you mentioned is indeed fixed in chrome beta, so the information I'm about to post is all in the beta version.

On Ubuntu Trusty on a VM, passing it gives a GPU error (some `mesa` library) unless the `--disable-gpu` flag is passed. If that flag is passed it fails with no specific error message: `Error: Browser exited unexpectedly`.

On Ubuntu Trusty on travis-ci (not dockerized), the `--disable-gpu` flag doesn't seem to be needed. It sill fails, but the error is more specific: `Gtk: cannot open display:`. This made me 🤔 and I started the `xvfb` and it passed, which it makes no sense, since precisely the point of `--headless` is to not need X server. This makes me think that it's not running headless despite of the flag.

On OSX sierra, as advertised, the headless works but not as expected. The `--headless` flag is being received by the browser, because it opens a chrome window **but doesn't render anything on it during the tests**. Without the flag you can see the test suite run. I assume that proves that browser args is working as expected.

The project is open source in case you want to check it yourself: cibernox/ember-basic-dropdown#256

At this point I lean to think that the problem is in chrome.

**Comment by jboler** [comment]
@cibernox I don't think there's a problem with Chrome because I can run my Watir specs using `--headless --disable-gpu` and it shows no Chrome window and runs much faster. There are some issues with extra components such as Selenium/Chromedriver/Webdriver expecting an X server for key mappings which will eventually get ironed out but chrome --headless works great without those components.

**Comment by cibernox** [comment]
@jboler Perhaps it's a timing thing. I hope someone with deeper understanding of testem could use my project to debug it. I wouldn't know where to start pulling the string.

**Comment by jboler** [comment]
Official support for this feature on Windows, Mac & Linux [lands in Chrome 59](https://www.chromestatus.com/feature/5678767817097216) so I will retest when that's released.

**Comment by calderas** [comment]
This is working fine for me locally on a Mac with the latest Chrome Canary 
>Version 59.0.3071.0 (Official Build) canary (64-bit)

```
brew install Caskroom/versions/google-chrome-canary
```

**Testem config:**
```
module.exports = {
  framework: 'qunit',
  test_page: 'tests/index.html?hidepassed',
  disable_watching: true,
  launch_in_ci: [ 'Chrome Canary' ],
  launch_in_dev: [ 'Chrome Canary' ],
  browser_args: {
    'Chrome Canary': [ '--headless', '--disable-gpu', '--remote-debugging-port=9222' ],
  },
};
```
When running you can navigate to this url to inspect [http://localhost:9222/](http://localhost:9222/)

**Comment by cibernox** [comment]
@calderas Actually the `--remote-debugging-port=9222` what the missing thing! I tried with Chrome 59 from the dev channel and it works (No need for canary apparently)

**Comment by jboler** [comment]
I can confirm that adding `--remote-debugging-port=9222` makes it work on Chrome 57 on Ubuntu! I have no idea why.

**Comment by joshuataylor** [comment]
Sorry for necro, but just for anyone looking for a reference, take a look at https://developers.google.com/web/updates/2017/04/headless-chrome .

```
chrome \
  --headless \                   # Runs Chrome in headless mode.
  --disable-gpu \                # Temporarily needed for now.
  --remote-debugging-port=9222 \
```

So the right params are here :+1:

**Comment by rondale-sc** [comment]
@cibernox what version of Chrome (that isn't canary) were you able to get running?  It works in Canary (for me), but without at Chrome 58.0.3029.11 it does not.  🍺

**Comment by johanneswuerbach** [comment]
> Headless Chrome is shipping in Chrome 59.

So, I guess currently beta and soon-ish stable. :-)

**Comment by paulbhartzog-ps** [comment]
Thanks everyone for this info. Saved my day. :-) 👍

**Comment by paulbhartzog** [comment]
Thx everyone for this info. Saved my day. 👍

**Comment by xdumaine** [comment]
We are still getting this error with latest testem. Everyone here seems to indicate it's working, but we're still getting the crash when passing those args. Any ideas?

**Comment by BryanCrotaz** [comment]
I'm seeing this fail on Shippable on Chrome 62.0

https://github.com/ember-cli/ember-cli/issues/7514

**Comment by erichonkanen** [comment]
what does `--disable-gpu` do? when I have that my qunit tests fail instantly with `Error: Browser exited unexpectedly.`

**Comment by dcombslinkedin** [comment]
@erichonkanen , did you ever find out the problem with your Error: Browser exited unexpectedly and --disable-gpu? We recently had an issue with getting Browser exited unexpectedly that was due to a config timeout setting, and I'm curious what happened with your issue.
