### ISSUE TITLE
chrome fails to connect

### ISSUE THREAD

**Issue by bastianl** [testem/testem#1107]
I recently did a clean install of MacOS and am getting this error for an ember project when running tests locally. They will run with Firefox and Safari but not Chrome. Does anyone have any pointers, or ideas why this could be happening? The tests pass locally through qunit, and out on CircleCI with testem.js..

```
$ ember test
WARNING: Node v7.8.0 is not tested against Ember CLI on your platform. We recommend that you use the most-recent "Active LTS" version of Node.js.
cleaning up...
Built project successfully. Stored in "/Users/user/my_project/tmp/class-tests_dist-HTULmc6w.tmp".
not ok 1 Chrome - error
    ---
        message: >
            Error: Browser failed to connect within 30s. testem.js not loaded?
            Stderr:
             2017-04-04 08:43:00.156 Google Chrome[70293:2408283] NSWindow warning: adding an unknown subview: <FullSizeContentView: 0x7fae8c0ad8b0>. Break on NSLog to debug.
            2017-04-04 08:43:00.156 Google Chrome[70293:2408283] Call stack:
            (
                "+callStackSymbols disabled for performance reasons"
            )
            [70296:775:0404/084300.405560:ERROR:child_thread_impl.cc(762)] Request for unknown Channel-associated interface: ui::mojom::GpuMain


        Log: |
            { type: 'error',
              text: 'Error: Browser failed to connect within 30s. testem.js not loaded?' }
            { type: 'error',
              text: '2017-04-04 08:43:00.156 Google Chrome[70293:2408283] NSWindow warning: adding an unknown subview: <FullSizeContentView: 0x7fae8c0ad8b0>. Break on NSLog to debug.\n2017-04-04 08:43:00.156 Google Chrome[70293:2408283] Call stack:\n(\n  "+callStackSymbols disabled for performance reasons"\n)\n[70296:775:0404/084300.405560:ERROR:child_thread_impl.cc(762)] Request for unknown Channel-associated interface: ui::mojom::GpuMain\n' }
    ...

1..1
# tests 1
# pass  0
# skip  0
# fail  1
Testem finished with non-zero exit code. Tests failed.
```

testem.js:
```
/* eslint node:true */

const config = {
  "framework": "qunit",
  "test_page": "tests/index.html?hidepassed",
  "disable_watching": true,
  "launch_in_ci": [
    "Chrome"
  ],
  "launch_in_dev": [
    "Chrome"
  ]
};

const CIRCLE_TEST_REPORTS = process.env.CIRCLE_TEST_REPORTS;

if (CIRCLE_TEST_REPORTS) {
  config.reporter = "xunit";
  config.report_file = `${CIRCLE_TEST_REPORTS}/ember/junit.xml`;
}

module.exports = config;
```

I tried reinstalling Chrome to no avail. Yarn, node (node 7.8.0 is installed as a dependency to yarn), and phantomjs are installed via brew. I have tried installing project packages with both npm and yarn, and I get the same failure with both.

Versions:
````
MacOS Sierra 10.12.14
node: v7.8.0
yarn: v0.21.3
npm: 4.2.0
ember: 2.6
ember-cli: 2.7.0-beta.6
phantomjs: 2.1.1
```

**Comment by johanneswuerbach** [comment]
Does `ember test --serve` actually work with chrome?

**Comment by bastianl** [comment]
Apparently not on my machine. However I know other developers are successfully running `ember test` (no server) with Chrome. I get the following error: 
```
Browser "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome --user-data-dir=/var/folders/xp/xr7w8fss4yxcx1phfdg3436r0000gn/T/testem-9234 --no-default-browser-check --no-first-run --ignore-certificate-errors --test-type --disable-renderer-backgrounding --disable-background-timer-throttling http://localhost:7357/9234/tests/index.html?hidepassed" failed
 to connect. testem.js not loaded?
```
However when I enter the indicated url in chrome, the tests pop up and run through qunit.

**Comment by johanneswuerbach** [comment]
What happens if you execute this command manually in your console?

**Comment by bastianl** [comment]
When I run `ember test --server` manually, I get the error message mentioned above. Attached is a screenshot.

<img width="1280" alt="screen shot 2017-04-08 at 9 00 37 am" src="https://cloud.githubusercontent.com/assets/8620425/24826589/edcb7cc2-1c39-11e7-84fe-eeaee59e1d16.png">

**Comment by johanneswuerbach** [comment]
Is Chrome actually starting? It should autostart once you start testem, is the path correctly pointing to your installed Chrome?

**Comment by johanneswuerbach** [comment]
Also what happens if you run the cmd manually in your console?

**Comment by bastianl** [comment]
When I run the command manually Chrome appears to open. I get the following output:
```
➜ /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --user-data-dir=/var/folders/xp/xr7w8fss4yxcx1phfdg3436r0000gn/T/testem-6403--no-default-browser-check --no-first-run --ignore-certificate-errors --test-type --disable-renderer-backgrounding --disable-background-timer-throttling http://localhost:7357/6403/tests/index.html\?hidepassed
2017-04-08 10:19:35.459 Google Chrome[90054:3205545] NSWindow warning: adding an unknown subview: <FullSizeContentView: 0x7fb11e563660>. Break on NSLog to debug.
2017-04-08 10:19:35.459 Google Chrome[90054:3205545] Call stack:
(
    "+callStackSymbols disabled for performance reasons"
)
[90057:775:0408/101935.752575:ERROR:child_thread_impl.cc(762)] Request for unknown Channel-associated interface: ui::mojom::GpuMain
2017-04-08 10:19:57.125 Google Chrome[90054:3205550] Spell server connection invalidated
```
However the chrome window is blank as the server is not running. So it can't connect on port 7357.

When I type `ember test --server` a new chrome window pops up, but I get the spinning wheel of death and the window does not load. I also can't open the dev console, or close the window... it appears stuck (it closes when I quit the testem process).

**Comment by bastianl** [comment]
I've also reinstalled Chrome recently in an attempt to resolve this.. with no luck.

**Comment by bastianl** [comment]
this seems like a difficult issue to track down without direct access to my machine. @johanneswuerbach could anyone try to give me some pointers on how to narrow down why testem is failing to launch Chrome?

**Comment by johanneswuerbach** [comment]
🤔 you could enable specific the `testem-debug` flag in ember-cli to get some additional details https://github.com/ember-cli/ember-cli/pull/6535 and / or manually instrument https://github.com/testem/testem/blob/master/lib/process-ctl.js#L40-L46 to directly log all stdout / stderr.

**Comment by QuantumInformation** [comment]
I also get the issue on phantom locally:

![image](https://user-images.githubusercontent.com/216566/28940556-059f3190-788d-11e7-9a7a-49b108baffa8.png)

**Comment by Harishreddy-Bonikela** [comment]
@QuantumInformation were you able to debug and resolve this issue?

**Comment by QuantumInformation** [comment]
Not yet.

**Comment by QuantumInformation** [comment]
I'm actually having the issue with phantom, chrome works.

**Comment by Harishreddy-Bonikela** [comment]
Its even failing in chrome for me. Chrome version -58, ember-cli@1.13.15.
<img width="1295" alt="screen shot 2017-08-17 at 12 14 54 pm" src="https://user-images.githubusercontent.com/23057118/29422357-f4654216-8345-11e7-80ca-0746529d048a.png">

**Comment by alexnb** [comment]
I can confirm, on my CI server this behaviour occurs sporadically with IE, FF, chrome since years, from the beginning. We have hundreds of tests which are called using 
`
testem ci -b -R teamcity`

Interesting is the fact, that the error occurs max. once per browser. Meanwhile the tests are running on Win10 but it was exactly the same on Win7 before.
