### ISSUE TITLE
Custom Jasmine Setup Is Disabling Auto Rerun

### ISSUE THREAD

**Issue by calebeno** [testem/testem#1108]
I'm using testem as a runner during development of a web application.  It's been a great tool.  Recently, I was looking into some further customization, especially in regard to utilizing a locally installed version of jasmine rather than the pre-included one.  Here is the setup I currently have:

testem.json
```javascript
{
  "framework": "custom",
  "test_page": "testem.mustache",
  "src_files": [
    //...list of components and specs...
  ]
}
```

testem.mustache
```html
<!doctype html>
<html>
<head>
    <title>Testem</title>
    <link rel="stylesheet" href="node_modules/jasmine-core/lib/jasmine-core/jasmine.css">
    <script src="node_modules/jasmine-core/lib/jasmine-core/jasmine.js"></script>
    <script src="node_modules/jasmine-core/lib/jasmine-core/jasmine-html.js"></script>
    <script src="node_modules/jasmine-core/lib/jasmine-core/boot.js"></script>
    <script src="node_modules/testem/testem.js"></script>
    {{#serve_files}}
    <script src="{{src}}"></script>
    {{/serve_files}}
</head>
<body>
<body>
    <div id="jasmine_content"></div>
</body>
</body>
</html>
```

With this setup, when I connect to my running testem instance, I am redirected to the testem.mustache page and the tests load and run correctly.  The top of the web page and the source tab in the dev tools both indicate that the correct new version of jasmine is being used.  However, running the tests this way causes one issue.  The test runner in the browser window is now relying on a local version of testem instead of being connected to the testem instance in the command line runner.  This breaks any reporting in the runner and also breaks the auto-reload function on test changes.  Am I missing something in the setup to re-enable that or is this simply an incompatible feature?

Thank you for your time looking into this.

**Comment by johanneswuerbach** [comment]
Instead of using `<script src="node_modules/testem/testem.js"></script>`, this should work `<script src="/testem.js"></script>`. Testem serves its client und a special url.

Does that solve your issue?

**Comment by calebeno** [comment]
Yes, that was definitely what I was missing. I was using that example in the link for reference, but I miss-understood about the testem file and how it was being served. Thanks for clearing that up.
