### ISSUE TITLE
Publish 1.16.0 to NPM

### ISSUE THREAD

**Issue by chadhietala** [testem/testem#1114]
Looks like it 1.16.0 is tagged in the repo but not released to NPM. https://www.npmjs.com/package/testem

**Comment by rwjblue** [comment]
👍 - Thanks for pointing this out @chadhietala!

@johanneswuerbach - Any reason it was tagged an not published?

**Comment by johanneswuerbach** [comment]
Sorry, fixed. Was just a missed when tagging and isn't automated yet.
