### ISSUE TITLE
Can no longer inherit from internal reporters.

### ISSUE THREAD

**Issue by rwjblue** [testem/testem#1115]
As of https://github.com/testem/testem/pull/1083, the built-in reporters get an additional argument (the `config` object) passed into them. Prior to #1083 it was possible to extend one of the default reporters:

```js
// testem.js
const TapReporter = require('testem/lib/reporters').tap;
class FailureOnlyReporter extends TapReporter {
  constructor() {
    super(...arguments);
    this._reportCount = 0;
  }

  display(prefix, result) {
    this._reportCount++;

    if (!result.passed) {
      super(...arguments);
    }

    if (this._reportCount > 100) {
      this.out.write('pass count: ' + this.pass);
      this._reportCount = 0;
    }
  }
}

module.exports = {
  // ...snip...
  reporter: new FailureOnlyReporter()
}
```

(we do this in Travis for Ember because otherwise the logs end up being longer than the CI output allows and the builds are failed)

After #1083, it is no longer possible, because the `config` object itself is not available when we are instantiating the reporter. 

---

One possible solution would be to modify [this code](https://github.com/testem/testem/blob/master/lib/utils/reporter.js#L12-L19) to also check if the name is a function and if it is, then instantiate it in the same way that a string version is.

This would allow us to use:

```js
module.exports = {
  //...snip...
  reporter: FailureOnlyReporter
};
```

And Testem would instantiate itself...

**Comment by johanneswuerbach** [comment]
Sounds like a good fix before rethinking this for a 2.0. I'm currently a bit busy, would you have time to create a PR for this?
