### ISSUE TITLE
Testem should not terminate the process it is running in after completion

### ISSUE THREAD

**Issue by ControlTheBit** [testem/testem#1128]
As the title says.

Is there maybe already a flag that one can set to avoid this behavior?
Thanks in advance, you are doing a great job by the way :+1: 

**The use case we are facing:**
We are using testem in grunt on our build server, since we need a framework that allows us to run our tests in a real chrome - testem is perfect for that. 

Now our issue is, that as soon as we run testem in ci or dev mode and finish the testem task, the whole process (including grunt) ends. This is really annoying because this way the whole build is terminated.

**Comment by johanneswuerbach** [comment]
Testem shouldn't be killed in a special way so that sounds more  like a bug in grunt.

Could you share a repo, which includes a reproducible test case?

**Comment by ControlTheBit** [comment]
My feeling does not lead to a bug in grunt. Unfortunately, I currently don't have a small project where the problem could be reproduced. But I can already give you the following information:

- "grunt": "0.4.5"
- "grunt-testem-all": "0.2.1"

_Maybe to be more specific:_
The issue is you want to run Task A, B, testem, C, D
Executed are A, B, testem [process end]

And my config for testem in the Gruntfile:

```
testem: {
			options: {
				launch_in_ci: ['Chrome'],
				launch_in_dev: ['Chrome'],
				framework: "jasmine",
				xunit_exclude_stack: true,
				disable_watching: true,
				fail_on_zero_tests: true,
				bail_on_uncaught_error: true,
				test_page: testConfig.outfile,
				port: "<%= port %>",
				report_file: "../../some/Path/file.xml",
				reporter: "xunit",
				unsafe_file_serving: true
			},
			inDev: {
				options: {
					xunit_intermediate_output: true,
				}
			},
			inCi: {
				options: {
				}
			}
[...]
```

**Comment by ControlTheBit** [comment]
I wanted to build a small grunt project to reproduce this issue, but I can't get it to work because testem does no finish anymore due to this issue: https://github.com/testem/testem/issues/1075

Unfortunately I can't downgrade my node version, since I'm dependent on it.

**Comment by ControlTheBit** [comment]
Alright! Finally found the time to look into this.

**This is an issue in the grunt-testem-all plugin (https://github.com/Ashot-KR/grunt-testem-all).**
