### ISSUE TITLE
Mode-based browser arguments

### ISSUE THREAD

**Issue by trentmwillis** [testem/testem#1139]
_Pardon if this is already possible, I could not find a convenient method of doing this._

With the advent of `--headless` for Chrome, I'd like to be able to pass different arguments for the Chrome browser launcher depending on if I am launching in CI or Dev mode. This way I can run headless during CI but have the actual browser window during development.

Currently, however, if you define `browser_args` for Chrome they seem to apply regardless of the mode being run. I can work around this by having two separate configs (one specifying `browser_args` and the other not), but that is less than ideal.

The initial API I came up with in my head for supporting this would look something like:

```json
{
  "browser_args": {
    "chrome": {
      "mode": "ci",
      "args": [ "--headless", "--disable-gpu", "--remove-debugging-port=9222" ]
    }
  }
}
```

Or, alternatively:

```json
{
  "browser_args": {
    "ci": {
      "chrome": [ "--headless", "--disable-gpu", "--remove-debugging-port=9222" ]
    }
  }
}
```

Another potential alternative would be to just add a "Headless Chrome" built-in browser launcher, but I could see use cases with other browsers where passing arguments depending on mode could be convenient.

If any of the above ideas seems reasonable I'd be happy to submit a PR. Or, if there is an easy way to accomplish the above with existing functionality that'd be great as well!

**Comment by rwjblue** [comment]
FWIW, what I've done in the past for this was via conditional.

```js
// testem.js
const CI = !!process.env['CI'];

let options = {
  "framework": "qunit",
  "test_page": "tests/index.html?hidepassed",
  "disable_watching": true,
  "launch_in_ci": [
    "Chrome",
  ],
  "launch_in_dev": [
    "Chrome",
  ]
};

if (IS_CI) {
  options.browser_args = {
    "chrome": {
      "args": [ "--headless", "--disable-gpu", "--remove-debugging-port=9222" ]
    }
  };
}

module.exports = options;
```

Also, not sure if you've tested this, but if you navigate your browser to `http://localhost:9222` you can see the tests running, interact with the DOM, etc.

---

All that being said, I totally agree that we should have a way to specify browser args by mode.  I think I vaguely prefer the second example above, but either seemed good...

**Comment by johanneswuerbach** [comment]
Fixed by https://github.com/testem/testem/pull/1144
