### ISSUE TITLE
Launch multiple instances of same launcher?

### ISSUE THREAD

**Issue by bttf** [testem/testem#1153]
Hello,

Recently tried to replace `phantomjs` with `Chrome` in our `testem.js` configuration to opt for the Chrome headless option

We have an ember project, and, when we run our test server, we usually have `phantomjs` running beside an instance of Chrome browser. 

Since we're switching to Chrome headless, I'm having trouble figuring out how to spawn two Chrome's, one headless and one not. Is there any way to do this?

**Comment by johanneswuerbach** [comment]
The only possible way at the moment is to specific different browser args for test/ci mode https://github.com/testem/testem/pull/1144

**Comment by bttf** [comment]
That's what I'd like to do, but not sure how to specify different browser args for basically the same process (`"chrome"`)? The problem is one is headless, one isn't

**Comment by bttf** [comment]
Ah I see now, that we can set it by what  mode (`ci`/`dev`). Sorry for the confusion and thanks

**Comment by rwwagner90** [comment]
We have a need for this for testing two different window sizes. Do you have suggestions on how to run `Chrome` twice with two different window sizes?
