### ISSUE TITLE
AppVeyor build reveals a strange error

### ISSUE THREAD

**Issue by nicojs** [testem/testem#1159]
I'm not sure if this is the right channel to report this issue, if not, please point me to the right place.

In the app veyor build you can see this error:

```
npm WARN onload-script     at Function.Module._load (module.js:276:25)\nnpm WARN onload-script     at Module.require (module.js:353:17)\nnpm WARN onload-script     at require (internal/module.js:12:17)\nnpm WARN onload-script     at cb (C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\lib\\npm.js:289:9)\nnpm WARN onload-script     at C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\lib\\npm.js:382:14\nnpm WARN onload-script     at C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\lib\\config\\core.js:82:7\nnpm WARN onload-script     at Array.forEach (native)\nnpm WARN onload-script     at C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\lib\\config\\core.js:81:13\nnpm WARN onload-script  
```

https://ci.appveyor.com/project/johanneswuerbach/testem/build/1930#L1182

I'm also having these issues running on my windows 10 machine. Any ideas on how to resolve them? Or where these issues come from? I haven't got a clue where to start looking for answers.

**Comment by johanneswuerbach** [comment]
Sorry, while I've seen those before I don't really have an idea what those are about / how to fix them :-(

**Comment by stefanpenner** [comment]
will gladly reopen if this is still happening, and if some reproduction is provided.
