### ISSUE TITLE
Add duration to teamcity reporter

### ISSUE THREAD

**Issue by makepanic** [testem/testem#1186]
Hi,
can we add [`duration='<test_duration_in_milliseconds>'`](https://confluence.jetbrains.com/display/TCD65/Build+Script+Interaction+with+TeamCity#BuildScriptInteractionwithTeamCity-ReportingTests) to the teamcity reporter output?
Currently it doesn't report the test durations.

I'm unsure if this'll introduce a breaking change because the reporter output changes.
If it's ok, I'll create a PR to fix this.

**Comment by johanneswuerbach** [comment]
Sounds good to me 👍
