### ISSUE TITLE
Testem is looking for google-chrome binary on FreeBSD, when it's chrome

### ISSUE THREAD

**Issue by duncan-bayne** [testem/testem#1196]
I'm trying to run testem on a FreeBSD system, but it's not finding my browser binary:

```
not ok 1 Error
    ---
        message: >
            Launcher Chrome not found. Not installed?
    ...

1..1
# tests 1
# pass  0
# skip  0
# fail  1
Launcher Chrome not found. Not installed?
Error: Launcher Chrome not found. Not installed?
```

It's not looking on $PATH, because:

```
$ which chrome
/usr/local/bin/chrome
```

~~I last encountered this bug back in 2015, and raised [an issue](https://github.com/testem/testem/issues/449) then.  It seems like the behaviour persists.~~

~~Would you like me to submit a PR to fix testem to look in $PATH on *NIX systems?  It's the Right Thing To Do™ on those systems.~~

This seems to be because it's looking for `google-chrome`, not `chrome`.  If I symlink `/usr/local/bin/chrome` to point to `/usr/local/bin/google-chrome` the problem goes away.

**Comment by knownasilya** [comment]
I'm having a similar problem, but symlinking doesn't help. I think the problem might be with this line: https://github.com/testem/testem/blob/master/lib/fileutils.js#L13

Specifically that it checks that it's a file, and a symbolic link isn't a file, afaik. I even tested by adding 

```js
  browser_paths: {
    Chrome: '/usr/bin/google-chrome'
  }
```

In my config where `which google-chrome` returns the above.

**Comment by duncan-bayne** [comment]
Any interest in a PR for this?  Will close if not.
