### ISSUE TITLE
Cannot run against deployed application

### ISSUE THREAD

**Issue by pixelpax** [testem/testem#1206]
Is there a way for testem to access remote urls and run tests against a deployed app? 

I can't find this info anywhere. It seems that `visit` does not execute an http request, but rather just manipulates the ember SPA router somehow. Is there a way I could get tests to render inside of an iframe perhaps? Or get visit get the site itself? This seems necessary in order to most accurately and safely test a product staged for deployment

**Comment by stefanpenner** [comment]
This isn't currently a supported feature. It doesn't seem like an unreasonable feature to add, but sounds like it requires some design and thought to execute correctly.

I am marking this as a feature for future readers, but closing as it is not a bug. Although closed, discussions can still continue here.
