### ISSUE TITLE
parallel runs

### ISSUE THREAD

**Issue by BryanCrotaz** [testem/testem#1245]
I have a machine with a lot of cores and I would like to be able to split my test run across them by launching a browser on each with a subset of tests, then recombine the results at the end.

I thought this might be best achieved by adding a `parallel` option to testem that is agnostic to the launcher used.

Where in the architecture should I start looking to achieve this? Where would I need to integrate?

**Comment by stefanpenner** [comment]
For ember folks, we have been using `ember exam` with some success. But deeper integration doesn't sound bad.

I would likely look to see how `ember exam` handles this, and see what could be improved in testem to either support it automatically, or improve support for others.

**Comment by stefanpenner** [comment]
labelled as feature, but closing as it isn't a bug. Totally down for better parallel support, and would welcome contributions.
