### ISSUE TITLE
-bash: testem: command not found

### ISSUE THREAD

**Issue by mmessenger0719** [testem/testem#1249]
My mac updated and now my testem does not work. It is downloaded but when I try to run the testem command it gives me command not found error. Any help would be great

**Comment by melvyn-sopacua** [comment]
The quickest fix is to alias `testem` to `npx testem`. Read about npx and what it does using `man npx` - it does have some magic in it you should be aware of.

To alias the command use `alias testem='npx testem'`. Then go to your project root (the one containing `package.json`) and confirm it is working. If so, add it to your bash profile: `alias testem >> ~/.bash_profile`.

This should persist accross reboots.

**Comment by stefanpenner** [comment]
> My mac updated and now my testem does not work

This suggest something on your mac changed, and likely not something with testem.

It is possible that you previously had testem installed globally and now no longer. Running `npm install -g testem` should correct this, alternatively what @melvyn-sopacua suggested would also work.

Closing, but will gladly reopen if I mistunderstood the issue
