### ISSUE TITLE
Ember Cli test --host option is ignored by testem

### ISSUE THREAD

**Issue by robert-j-webb** [testem/testem#1255]
Hi, I noticed that I was broadcasting my testing server to my whole network. I opened an issue in ember-cli/ember-cli and we realized that testem is not passing in host to it's server argument.

Here's how to reproduce this issue:

```
nvm use v9.3.0 
npm install -g ember-cli@latest
mkdir hello
cd hello
ember init
ember test --serve --host 127.0.0.1
lsof -i -n -P | grep 7357
```

Observed output:
```
node      13529 robertwebb   22u  IPv6 0xXXXXXXXXXXXXX     0t0  TCP *:7357 (LISTEN)
node      13529 robertwebb   30u  IPv6 0xXXXXXXXXXXXXX      0t0  TCP 127.0.0.1:7357-127.0.0.1:56246 (ESTABLISHED)
```
Expected output:
```
node      13529 robertwebb   22u  IPv6 0xXXXXXXXXXXXXX      0t0  TCP 127.0.01:7357 (LISTEN)
node      13529 robertwebb   30u  IPv6 0xXXXXXXXXXXXXX     0t0  TCP 127.0.0.1:7357->127.0.0.1:56246 (ESTABLISHED)
```

Thankfully Robert Jackson found where the issue is in testem, it's right here: https://github.com/testem/testem/blob/ed17398452743afd0a4952d343c10bf07588ea7a/lib/server/index.js#L64

It should be passing in `this.config.get('host')`

Would you like a PR for this?

**Comment by stefanpenner** [comment]
@robert-j-webb good catch, yes I believe a PR would be good!

**Comment by robert-j-webb** [comment]
#1256 is actually the pr that fixes this - however it is failing a test for weird reasons. We haven’t figured out how to fix it yet I think.
