### ISSUE TITLE
Works Great!

### ISSUE THREAD

**Issue by JPKramer707** [testem/testem#1312]
Hi there!

Testem is awesome!

**Comment by JPKramer707** [comment]
Upgraded ember from 3.0.4 => 3.5.0, tried again. Result: Same.

**Comment by JPKramer707** [comment]
This is a tough one. Very difficult to reproduce, to comprehend, to wrap your head around. I don't envy you, dear reader. It is a complicated problem with no clear solution. If you surrender to the mystery, I don't hold it against you. Some people think that `testem` works in every case. This is a foolish and misguided philosophy - `testem` cannot work in every case. So I am posting this issue as proof, to those of excessive faith, that their idealized conception of `testem` is sadly misguided.

`testem` works 99% of the time, but it is not perfect. Just in case you want to argue to the contrary, I offer this simple test case as my witness.

If you believe I've fabricated this entire issue to defame `testem`, I ask that you simply try it yourself. It's a one-line console command. Here it is:

$ ember new testem-test; cd testem-test; testem;

Peace and goodwill be upon you, dear reader. Namaste.

**Comment by jonathansamines** [comment]
@JPKramer707 I don't think an ember application is designed to use testem directly. What you probably want is just a `ember test --serve` or `npm t -- --serve`. Hope it helps.
