### ISSUE TITLE
Add support for Brave browser

### ISSUE THREAD

**Issue by raido** [testem/testem#1339]
Would be nice if https://brave.com browser was also available in known browser config: https://github.com/testem/testem/blob/47773ffe85627d7486496e5999082b01b4add222/lib/utils/known-browsers.js

**Comment by stefanpenner** [comment]
We would accept a PR adding built-in support for it.

**Comment by ming-codes** [comment]
The MacOS path is similar to Chrome. Anyone knows what's the path for Windows?
