### ISSUE TITLE
ES2018 Issue

### ISSUE THREAD

**Issue by thomashzhang** [testem/testem#1343]
We are using ES2018 in our Typescript target, tsconfig.json is like so:
```
{
    "compilerOptions": {
        "target": "ES2018",
        "module": "commonjs",
       ...
}
```
This translates the following TypeScript:
`export class TestTimeConstant {`

To:
`Object.defineProperty(exports, "__esModule", { value: true });`

This fails in Testem like so:
`Global error: Uncaught ReferenceError: exports is not defined at http://localhost:7357/built/tests/XXX/YYY/ZZZ/TestSomething.js, line 2`

All our tests run fine in mocha. We would love to get Testem working -- what should we do?

**Comment by stefanpenner** [comment]
Sorry I don't follow, is testem not compiling your code correctly?  Can you provide a reproduction?

**Comment by cdaringe** [comment]
if you open your browser, you will notice that `window.exports` is not a thing.  your browser doesn't understand commonjs, thus, you receive this error.  i think what you end up needing to do is bundle your tests w/ webpack or browserify

**Comment by cdaringe** [comment]
recommend issue for closure.  this case is covered by the bundling recipes (browserify, webpack)

**Comment by stefanpenner** [comment]
@cdaringe Yes, I agree with you. Testem is merely a runner, building/compiling/bundling should occur separately.
