### ISSUE TITLE
Releasing v3.0.0

### ISSUE THREAD

**Issue by step2yeung** [testem/testem#1379]
<img width="744" alt="Screen Shot 2019-09-30 at 8 47 03 AM" src="https://user-images.githubusercontent.com/9669889/65895146-d36c5000-e35f-11e9-887a-2c6749e56537.png">
@stefanpenner @johanneswuerbach Going to release v3.0.0 with the recent changes :)

**Comment by stefanpenner** [comment]
:shipit: 🕺

**Comment by step2yeung** [comment]
Released v3.0.0!
