### ISSUE TITLE
Upgrade xmldom package

### ISSUE THREAD

**Issue by dominicroessner** [testem/testem#1443]
testem currently uses version 0.1.27 of xmldom in the package-lock.json. There is a known security vulnerability that requires xmldom to be 0.5.0 or later. Details of this vulnerability can be found here: https://github.com/advisories/GHSA-h6q6-9hqw-rwfv

**Comment by johanneswuerbach** [comment]
See https://github.com/testem/testem/pull/1421#discussion_r594394481

**Comment by johanneswuerbach** [comment]
Fixed in `3.4.1`
