### ISSUE TITLE
Upgrade printf package

### ISSUE THREAD

**Issue by dominicroessner** [testem/testem#1444]
testem currently uses version 0.5.1 of printf in the package-lock.json. There is a known security vulnerability that requires printf to be 0.6.1 or later. Details of this vulnerability can be found here: https://github.com/advisories/GHSA-xfhp-gmh8-r8v2

**Comment by johanneswuerbach** [comment]
Fixed in https://github.com/testem/testem/releases/tag/v3.4.0
