### ISSUE TITLE
Upgrade socket.io to 4.5.4

### ISSUE THREAD

**Issue by JgJun** [testem/testem#1613]
testem is using  "socket.io": "^4.1.2", which is using [`"engine.io": "~5.1.0",`](https://github.com/socketio/socket.io/blob/4.1.2/package.json#L54).  `engine.io@5.1.0` has vulnerable  https://github.com/advisories/GHSA-273r-mgr4-v34f

[`socket.io@4.5.4`](https://github.com/socketio/socket.io/releases/tag/4.5.4) uses the fixed version  [`engine.io@~6.2.1`](https://github.com/socketio/engine.io-client/tree/6.2.1)

**Comment by johanneswuerbach** [comment]
The existing `^4.1.2` should already allow `4.5.4`, but a PR doing an explicit bump is welcome :-)

<img width="1046" alt="image" src="https://user-images.githubusercontent.com/864578/206663961-9cd5f8db-cba6-40da-b8f2-d3a404373c68.png">

https://semver.npmjs.com/

**Comment by johanneswuerbach** [comment]
Closed in https://github.com/testem/testem/pull/1751
