### ISSUE TITLE
testem server becoming slower and slower

### ISSUE THREAD

**Issue by langalex** [testem/testem#1681]
Hi,

I have an Ember app that uses web workers. When running my test suite, the worker*.js files get loaded again and again from the testem web server. For some odd reason, serving thoses files becomes slower and slower as the tests suite progresses, but also faster again:

<img width="561" alt="image" src="https://github.com/testem/testem/assets/2173/386ff319-7e76-41f4-ba48-91b74eb04523">

As you can see, initially the files are served in 1ms, but the time goes up to 32s, and then down again. I also noticed that when this happens, the testem UI becomes unresponsive, and the only way to kill the process is via `kill -9`.

Any idea how to debug this?

I was also thinking of adding an expires header with a long expiry time to prevent the browser from re-requesting the files. Any chance such a PR would get accepted?

I'm using testem 3.10.1, node 16.19.0.

**Comment by runspired** [comment]
This is likely due to the memory leak in testem I typically fix by patching over the emit:

```html
		<script type="text/javascript">

			// Testem is not loaded when you visit /tests
			if (typeof Testem !== 'undefined') {
				// disable testem log output
				// by default testem serializes all of these logs
				// and transmits them through the websocket even if
				// the reporter is configured to ignore them. This results
				// in extremely high memory and cpu utilization and eventually
				// will crash the console.
				const ignoredLogTypes = new Set(['log', 'warn', 'info', 'group']);
				// restore original functionality
				ignoredLogTypes.forEach((method) => {
					console[method] = Testem.console[method];
				});
			}
		</script>
```

I've been meaning to upstream making this configurable. I can understand why some folks might want this logging and some reporters might want to handle receiving it, but currently its just an unbounded append-only array with significant costs to both the browser and the test server

**Comment by langalex** [comment]
this looks to be a duplicate of #1356. closing.
