### ISSUE TITLE
Is there way to run functional tests?

### ISSUE THREAD

**Issue by stereobooster** [testem/testem#176]
Something like this

``` js
describe('PhoneCat App', function() {
  describe('Phone list view', function() {
    beforeEach(function() {
      browser().navigateTo('../../app/index.html');
    });

    it('should filter the phone list as user types into the search box', function() {
      expect(repeater('.phones li').count()).toBe(3);
      input('query').enter('nexus');
      expect(repeater('.phones li').count()).toBe(1);
      input('query').enter('motorola');
      expect(repeater('.phones li').count()).toBe(2);
    });
  });
});
```

AngularJS + testacular doing this. But actually magic `browser().navigateTo('');` tightly connected to AngularJS. So I cant do it for EmberJS (actually I can if I port `ngScenario` for Ember) .

So is there a way to do something like this in testem?

**Comment by spinlock99** [comment]
@wilmoore did you ever get a casper runner up and .... running? We're looking to do the same thing.

**Comment by wilmoore** [comment]
@spinlock99 I ended up going with http://webdriver.io.

**Comment by spinlock99** [comment]
Nice @wilmoore. We use webdrive.io as well. I have to admit that it's really hard to write good tests with webdriver though. We get different results almost every time we run them.

**Comment by alexindigo** [comment]
I've created `buster-functional` some time ago for lightweight (developer-oriented) functional testing, but I'm yet to make it work with `testem` _(still waiting for a free weekend)_. :)
