### ISSUE TITLE
node processes get orphaned

### ISSUE THREAD

**Issue by Raynos** [testem/testem#199]
When I start a server on a PORT in my tests and run it with testem sometimes this process gets orphaned.

This means that when I close testem and try to run the test again manually with `npm test` I get an `EADDRINUSE` error because the node process testem spawned is still running. Since testem was already closed this process has been orphaned and there is no way to kill it other then `killall node` or careful looking.

**Comment by iclanzan** [comment]
Just ran into this problem today. Would appreciate a fix.

**Comment by johanneswuerbach** [comment]
Hey, could you provide a simple repo / process script to reproduce this?

Thanks

**Comment by iclanzan** [comment]
I can’t seem to be able to reproduce it. It only happened once. I am using `tape`. I guess there isn’t anything that can be done until the bug can be reproduced reliably.

**Comment by johanneswuerbach** [comment]
This should no longer happen with `v1.11.0`

**Comment by kylecordes** [comment]
I'm pretty sure this happened to me today with 1.16.1. I was able to find and kill -9 the orphaned process, to get up and running again.
