### ISSUE TITLE
Allow testem ci console messages through to stdout

### ISSUE THREAD

**Issue by dbashford** [testem/testem#210]
re: https://groups.google.com/forum/#!topic/testem-users/mE83jGLs9eo

It would be nice if there was some means to have testem ci to let console messages through.  Best thing that comes to mind is a flag on the command itself.

**Comment by johanneswuerbach** [comment]
No, it's just needs to be embedded into the tap out (maybe as comments http://en.wikipedia.org/wiki/Test_Anything_Protocol)

**Comment by JarrodCTaylor** [comment]
I believe that this should have been closed with PR #402
