### ISSUE TITLE
Bind to specific userAgent for custom launcher

### ISSUE THREAD

**Issue by mgcrea** [testem/testem#216]
I have been working on a custom [iOS browser](https://github.com/mgcrea/node-ios-browser), here is the configuration I use:

    "launchers": {
      "ios": {
        "command": "ios-browser http://localhost:7357"
      }
    },

However, when the iOS simulator pops up, it is catched as a new browser in a new tab with the following userAgent:

    Mozilla/5.0 (iPhone; CPU iPhone OS 6_1 like Mac OS X) AppleWebKit/536.26 (KHTML, like Gecko) Mobile/10B141 (154578640)

Would be great to be able to define a custom regex to "catch" a connecting browser from a custom launcher.

**Comment by johanneswuerbach** [comment]
Having a user-agent match as solution for the issue you describe feels like a workaround for me. You can already make testem match spawned process with connected browser using:

```
"launchers": {
  "ios": {
    "command": "ios-browser <url>",
    "protocol": "browser"
  }
},
```
