### ISSUE TITLE
Scripts are not accessible with the latest version of Node (0.10.5)

### ISSUE THREAD

**Issue by cavneb** [testem/testem#217]
OSX 10.8.3
Node: v0.10.5

I am. If I run `testem` in any folder and open up the url http://localhost:7357. It appears that the reason for the failure is that it cannot access the scripts. 

Screenshots:

![screen shot 2013-05-20 at 11 52 12 am](https://f.cloud.github.com/assets/12481/537601/16b919fa-c176-11e2-9d23-bd19ad04339f.png)

![screen shot 2013-05-20 at 11 51 13 am](https://f.cloud.github.com/assets/12481/537602/19f72062-c176-11e2-882a-2c4d6c7eaf85.png)

**Comment by shivamadhavan** [comment]
Would like to reopen this issue. It is not persistent however, happens at random. Is this a testem issue or an express one ?
```
_http_outgoing.js:331
    throw new Error('Can\'t set headers after they are sent.');
          ^
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:331:11)
    at ServerResponse.res.setHeader (C:\Users\EXILANT\AppData\Roaming\npm\node_m
odules\testem\node_modules\express\node_modules\connect\lib\patch.js:59:22)
    at SendStream.setHeader (C:\Users\EXILANT\AppData\Roaming\npm\node_modules\t
estem\node_modules\express\node_modules\send\lib\send.js:471:44)
    at SendStream.send (C:\Users\EXILANT\AppData\Roaming\npm\node_modules\testem
\node_modules\express\node_modules\send\lib\send.js:347:8)
    at C:\Users\EXILANT\AppData\Roaming\npm\node_modules\testem\node_modules\exp
ress\node_modules\send\lib\send.js:325:10
    at Object.oncomplete (fs.js:93:15)
```

**Comment by johanneswuerbach** [comment]
@shivamadhavan, which version of testem and node are you using? Do you have a repo to replicate this case?

**Comment by shivamadhavan** [comment]
I am using node 0.11.14, 
testem - 6.39

The issue is intermittent. I can setup a repo to reproduce within the next few days.

**Comment by johanneswuerbach** [comment]
Any chance setting up the repo?

**Comment by miparnisari** [comment]
I can reproduce this bug in Windows 10 and Node 4.4.2. Demo repo here: https://github.com/miparnisari/myangular

![testem error](https://cloud.githubusercontent.com/assets/5374887/14549985/407d86f4-029b-11e6-99a8-31dae398062a.png)
