### ISSUE TITLE
Support for slimer.js

### ISSUE THREAD

**Issue by szkrd** [testem/testem#256]
It would be nice if testem would have slimerjs support (slimer is like phantom, but with a gecko engine)?

http://docs.slimerjs.org/current/differences-with-phantomjs.html

**Comment by geoffberger** [comment]
@szkrd I know this was a while ago, but did you come across a solution for this?

**Comment by szkrd** [comment]
As far as I can recall, I haven't, but yeah, it was a while ago :)

**Comment by geoffberger** [comment]
For whatever it's worth, my use case wasn't for slimerjs but another headless browser, so I'd imagine the implementation would look similar. I got it working for my use case, but I'd imagine it would look something like this for slimerjs:

```
"slimerjs": {
  "command": "slimerjs slimerjs-launcher.js <url>",
  "protocol": "browser"
}
```

where slimerjs-launcher.js would be similar to phantomjs launcher that comes with testem:

https://github.com/airportyh/testem/blob/master/assets/phantom.js

The thing I didn't know about was the <url> token.

**Comment by johanneswuerbach** [comment]
Good to know, they should be documented somewhere.
