### ISSUE TITLE
Feature Request: 'resource_root' in config file

### ISSUE THREAD

**Issue by breathe** [testem/testem#258]
I'm using testem to run integration tests of an emberjs application.  I'm using the test_page option and referencing an html file which should load my application as well as all the testing resources.

This testrunner.html page for my app is essentially the same thing as my app's index.html plus a few additional resources that have to be loaded for the purpose of setting up the testing environment -- namely:
- /testem.js
- the test framework (qunit)
- the test framework's css
- and the tests themselves

When I run testem, the testem server starts with the current working directory as the server's 'resource root' directory -- lookups for javascript, json, css, img, or any other static resources will occur relative to the directory from which I run testem.  What I would like is for the resource root to refer to the root directory where all my projects static web assets live.

Without this option, the only way I can get things to to behave correctly is to put my testem.json in the root of web assets directory rather than the root of my whole project.

It would be better to be able to specify the root directory ...

For example -- given a config like this

```
{
  "test_page": "./public/testrunner.html",
  "resource_root": "./public/",
  "launch_in_dev": [
    "Firefox",
    "Chrome"
  ],
  "launch_in_ci": [
    "PhantomJS"
  ]
}
```

After invoking testem, a request against the testem http server for the resource '/img/foo.jpeg' would resolve to the underlying file at './public/img/foo.jpeg'

**Comment by prabirshrestha** [comment]
@airportyh are there any plans to support `baseUrl` similar to karma?

```json
{
  "test_page": "test/testrunner.html",
  "baseUrl": "../../",
  "launch_in_dev": [
    "Firefox",
    "Chrome"
  ],
  "launch_in_ci": [
    "PhantomJS"
  ]
}
```

**Comment by airportyh** [comment]
@prabirshrestha I am not working on it actively now, but PRs will be considered.

**Comment by prabirshrestha** [comment]
@airportyh could you point me to where i can add this since i'm not familiar with the codebase. If I have time I can then try to send a PR for it.

**Comment by airportyh** [comment]
Read [CONTRIBUTING.md] if you haven't. For this feature the most relevant code is in https://github.com/airportyh/testem/blob/master/lib/server/index.js
