### ISSUE TITLE
Option to make "testem ci" run using random port.

### ISSUE THREAD

**Issue by merio** [testem/testem#283]
Having a fixed port prevents testem to be run by multiple users in the same machine at the same time.
I'm workarounding this by finding an available port to pass to testem's command line, but it would be nice for testem to handle this in its own.

**Comment by darrennolan** [comment]
Was this particular ticket closed due to lack of activity or interest?

Find i'm facing the same issue now, where in ci multiple projects building out on the same server are unable to do so at the same time - due to all of them using the same port.

**Comment by darrennolan** [comment]
Just found https://github.com/testem/testem/issues/842 - use port `0`.  Will look into this, thank you.
