### ISSUE TITLE
Bundle phantomjs via npm dependency?

### ISSUE THREAD

**Issue by ruudud** [testem/testem#343]
Are there any good arguments against bundling phantomjs with this package?

https://npmjs.org/package/phantomjs -- this package supports both Windows, OSX and Linux.

The reason I'm asking is that this would make it alot easier to add testem as a dependency in my project's package.json and run `node_modules/.bin/testem` to test my code. Now I have to add phantomjs as a dependency myself, and fiddle with PATH for testem to recognize phantom as an available browser.

**Comment by flecno** [comment]
FYI: You can use your local phantomjs in the current pre-release 0.7.0 see #486. And yes - phantomjs is huge but you can define your own download source: https://github.com/Medium/phantomjs#custom-binaries-url

**Comment by airportyh** [comment]
@flecno that seems a good enough solution. Add phantomjs to your devDependencies and you should be good to go.
