### ISSUE TITLE
Cannot delete node_modules directory; file path too long

### ISSUE THREAD

**Issue by jerrod-williams** [testem/testem#357]
I'm writing some ruby rake tools to help us out with our shift toward SPAs. We currently use Mimosa and were evaluating testem against karma. One issue I've seen while trying to implement a rake clean against our JS apps is that the deletion of the node_modules folder fail in all applications that use/require testem. My only solution so far is to manually rename the directories in the chain to a single letter to get it down to a path size that Windows is able to delete. This is quite a pain.

Just wanted to share as my Google searches have come up empty-handed.

**Comment by studio174** [comment]
I made a script to help delete node_modules folder:

https://github.com/studio174/node-cleanup

**Comment by ayman-alkom** [comment]
http://stackoverflow.com/a/34565762/2580499

**Comment by mathewbeno** [comment]
http://stackoverflow.com/a/34565762/2580499 

It worked for me 

Thank you
