### ISSUE TITLE
Hard to listen to all-test-results event

### ISSUE THREAD

**Issue by piuccio** [testem/testem#360]
The code of testem client is

```js
window.Testem = {
  emit: function(evt){
    var args = Array.prototype.slice.apply(arguments)
    socket.emit.apply(socket, circularSafe(args))
    if (this.evtHandlers && this.evtHandlers[evt]){
      var handlers = this.evtHandlers[evt]
      var args = Array.prototype.slice.call(arguments, 1)
      for (var i = 0; i < handlers.length; i++){
        var handler = handlers[i]
        handler.apply(this, args)
      }
    }
  },
```

Which means, first the socket then the callbacks. In case of `all-test-results`, the socket message tells `testem ci` to kill the browser, so depending on how quick this happen, the handler callback might not be called.

It would be good to move the socket.emit at the end of the method

**Comment by tandrewnichols** [comment]
I was able to work around this by setting a timeout in `lib/ci/browser_test_runner.js` in the `onAllTestResults` handler. My changes look like this:

```js
  onAllTestResults: function(results){
    var self = this
    setTimeout(function() {
      self.launcher.kill(null, function(){
        self.finish()
      })
    }, 50);
  },
```

As you can see, you don't need much of a timeout (maybe depending on how performant your coverage server is). I tried it down to 10, but at 10, it was sometimes inconsistent. At 50, it seemed to generate the report reliably for me (and that's still pretty fast - you don't notice the delay at all). @airportyh - Is this a viable fix that could be merged? It seems a bit hackish, and you might prefer something more legit, but this does solve the problem. You could always merge it as a temporary fix to be replaced later with something better.

**Comment by piuccio** [comment]
As a matter of facts, `grunt-testem` is also using a 50ms timeout.

**Comment by tandrewnichols** [comment]
Well . . . this still doesn't work in PhantomJS. Works with Chrome. I mean . . . the timeout happens (logging stuff tells me so), but it's hard to know if my script that sends coverage to the server is working. Adding `console.log` does nothing. _Should_ I be seeing logs in the terminal when running under phantom?

**Comment by johanneswuerbach** [comment]
Which testem and node version are you using?

**Comment by tandrewnichols** [comment]
Node v0.10.33
Testem v0.6.24 from [here](https://github.com/tandrewnichols/testem)

**Comment by matteius** [comment]
Regardless of the question how effective is adding a timeout (from the answer book: not very, because it relays on an inherent race condition existing in the system) as a Computer Engineer I would not approve a timeout based solution--clearly anyone could add one.

Couldn't the author explain how to add an event that is capture the coverage results???

**Comment by tonylukasavage** [comment]
I believe I'm encountering the same thing, specifically with the scenario of trying to deliver istanbul coverage results after testem finishes running phantomjs (chrome works fine). Any movement on this in terms of a solution or reliable workaround?

**Comment by efx** [comment]
+1. Seeing this in an ember-cli app

**Comment by jreading** [comment]
I'm seeing this too now.

**Comment by jreading** [comment]
I have been thinking about this and wondering if it makes sense to implement a "sendCoverage" or similar functionality via a config. This seems like a very common use-case, it might sense to wrap the kill command that gets fired on "onAllTestResults" with a check for this flag and run kill on the updated readyState (done) from the ajax request. The URI and port can come from the config. Thoughts? This is a big issue in one of our apps that has a fairly large coverage file.

**Comment by johanneswuerbach** [comment]
I would prefer to have a more generic way to register async afterTests / beforeTests hooks, but would gladly accept a PR.

**Comment by efx** [comment]
A generic way would be lovely. @jreading These lines shutdown the browser process: https://github.com/testem/testem/blob/master/lib/runners/browser_test_runner.js#L145-L149
As a demonstration you can remove `this.finish()` and your coverage sending should finish with the test server process never finishing :) 
A simple approach would be to call `this.finish` after a callback as supplied by the configuration. If I get time I can try PRing something to this effect.

**Comment by jreading** [comment]
I'm working through an "afterTests" queue that handles async callbacks. PR later today and of course open for comments.
