### ISSUE TITLE
Missing Chromedriver or browser causes silent failure

### ISSUE THREAD

**Issue by duncan-bayne** [testem/testem#361]
If either Chrome or Chromedriver is missing or can't be executed, then `testem ci` claims there are 0 tests and passes:

````
 $ ber testem
1..0
# tests 0
# pass  0
# fail  0

# ok
````

Reproduction is easy; on my Linux Mint system I just remove Chrome with `sudo dpkg --remove google-chrome-stable`.

(I'm in the process of fixing this and will submit a pull request).

**Comment by johanneswuerbach** [comment]
This should be resolved in the latest testem version. You can install it using npm install -g testem@1.
