### ISSUE TITLE
console.log output is still [object Object]

### ISSUE THREAD

**Issue by mnichols** [testem/testem#394]
I see this commit a year ago (https://github.com/Raynos/testem/commit/e0d2a23c171f81a926fde73595b580805ed55077), and then later it was made circularSafe but I am still seeing the annoying [object Object] printout when i try to log during tests. I am using the 'mocha' framework if that matters. Any idea what i need to do to make it sane?

**Comment by Cmdv** [comment]
Would be great if there was a way around this as when doing a bit of TDD, it's really difficult if you can look through specific objects via `console.log()`.

how do people get around it otherwise?

**Comment by johanneswuerbach** [comment]
@mnichols could you try testem master?
