### ISSUE TITLE
How to actually create and use custom adapter?

### ISSUE THREAD

**Issue by kimmobrunfeldt** [testem/testem#423]
I am trying to do adapter for [jest](https://github.com/facebook/jest) but looking at the example raised some questions:
- How should I add jest framework to testem? Just by adding jest.js file to a custom test.html page?
- How do you point the custom adapter to testem? In the example, .testem.json had "framework": "custom" and adapter was named customAdapter.js but where should the adapter.js file be located relative to .testem.json and how should it be named? 
- I looked some [test runners already in the project](https://github.com/airportyh/testem/blob/master/public/testem/) and there are quite a few files. For example jasmine2: _jasmine2.css_, _jasmine2.js_, _jasmine2-html.js_, _jasmine2-boot.js_, _jasmine2_adapter.js_. I didn't see explanations in readme. What are the files and should I create all these for jest too?

**Comment by ecasilla** [comment]
+1

**Comment by airportyh** [comment]
To use the custom adapters feature, you would go by this example: https://github.com/airportyh/testem/tree/master/examples/custom_adapter

The custom adapter file doesn't need to be named anything different, it just needs to be loaded as one of the source files loaded by testem. You can do that by including in in `src_files`, or by default testem loads all files in the current working directory. The way that testem actually registers it as a custom adapter is via the `Testem.useCustomAdapter(yourAdapter)` method: https://github.com/airportyh/testem/blob/master/examples/custom_adapter/customAdapter.js#L120
