### ISSUE TITLE
How to configure testem to disable cors in chrome and phantomJS

### ISSUE THREAD

**Issue by peterheard01** [testem/testem#427]
We have the spec...
{
  "framework" : "jasmine",
  "launch_in_dev" : ["Chrome"],
  "launch_in_ci" : ["PhantomJS"],
  "src_files" : [
    "generated/js/app.js",
    "generated/js/spec-int.js"
  ]
}

I would just like to know is it possible to disable CORS with both Chrome and PhantomJS? Do I have to put in some more configuration?

**Comment by johanneswuerbach** [comment]
At the moment it is not possible to attach custom arguments to launchers.

**Comment by johanneswuerbach** [comment]
Since `v1.11.0` customising default launcher arguments is possible https://github.com/testem/testem/tree/v1.11.0#customizing-browser-arguments
