### ISSUE TITLE
Suggestion: Use node-notifier instead of Growl directly

### ISSUE THREAD

**Issue by FredyC** [testem/testem#445]
Just found out about this ... https://www.npmjs.com/package/node-notifier

It's cross platform with fallback to Growl which is used now.

Edit: Thing is, that with Growl I am getting duplicate notifications for some reason, so I am not using it really.

**Comment by johanneswuerbach** [comment]
Feel free to send a PR, I'm currently not using the Growl notifier and don't really have time to look into issues here.
