### ISSUE TITLE
TAP results should still respect exit status code

### ISSUE THREAD

**Issue by jasonkarns** [testem/testem#527]
The TAP result parser correctly shows the pass/total test results in the tab. However, if there is an error in the process that isn't caught by the testing framework (say, outside of a test or in an after hook or similar), then it's possible for the process to exit with a non-zero status code. In such a scenario, the tab is rendered Green since the TAP results reported successful, even though the process errored.

I think that the exit status code should be respected, even when given TAP output. `launcher 20/20` (or whatever) in the tab name is still fine, but it should be colored red if exit status code is non-zero.

![fd71e7aa-c98f-11e4-86e0-2d19e36f6d59](https://cloud.githubusercontent.com/assets/119972/6923367/3da074d2-d79f-11e4-9538-d65a8184b2ed.png)

**Comment by jasonkarns** [comment]
I think this is related to #131

**Comment by johanneswuerbach** [comment]
This should be resolved in master.
