### ISSUE TITLE
testem ci not exiting

### ISSUE THREAD

**Issue by cdaringe** [testem/testem#528]
Hello:

I have a test suite for testing an offline storage wrapper.  my `npm test` script executes `testem ci`.  The script runs as expected, but then hangs.  Any advice on what to inspect for?

Thanks!

-Chris

testem.json:
```json
{
    "framework": "mocha",
    "src_files": [
        "test/*.js"
    ],
    "serve_files": [
        "bundle.js"
    ],
    "before_tests": "browserify test/* > bundle.js",
    "on_exit": "rm bundle.js",
    "launch_in_dev": ["PhantomJS"]
}
```

phantom.js version
```bash
 % phantomjs -v                                                                                                                           client/local (feature/ocoins-client-class-improvement ⚡) chrisweb
1.9.8
```

script output:
```bash
 % npm test                                                                                                                               client/local (feature/ocoins-client-class-improvement ⚡) chrisweb

> coins-offline-db@1.0.0 test /var/www/html/coins_core/js/client/local
> testem ci

ok 1 PhantomJS 1.9 - basic db operations should support retrieving the schema
ok 2 PhantomJS 1.9 - basic db operations should have oCOINS stores
ok 3 PhantomJS 1.9 - basic db operations should support adding a record
ok 4 PhantomJS 1.9 - basic db operations should support counting items in the store
ok 5 PhantomJS 1.9 - basic db operations should support clearing the store
ok 6 PhantomJS 1.9 - basic db operations should be able to fetch all records from a store
ok 7 PhantomJS 1.9 - basic db operations should be able to fetch records on dbid
ok 8 PhantomJS 1.9 - basic db operations should be able to fetch records on simple filter
ok 9 PhantomJS 1.9 - basic db operations should support updating a record
ok 10 PhantomJS 1.9 - basic db operations should support removing a record
ok 11 PhantomJS 1.9 - basic db operations should support removing all records from store

1..11
# tests 11
# pass  11
# fail  0

# ok
```

[Test File](https://gist.github.com/cdaringe/6e5b8c85cd2201a28749)

**Comment by sakabako** [comment]
I'm having the same issue with all browsers while using `testem ci`.

node: v0.10.32
testem: 0.8.3

**Comment by johanneswuerbach** [comment]
Could anybody provide a sample repository which triggers this issue? Otherwise it's nearly impossible for me to track down. Thanks :smile:

**Comment by sakabako** [comment]
Sure, this one: https://github.com/compstak/rolling-storage/

**Comment by sakabako** [comment]
it's the jasmine clock stuff. If you comment out the third spec file it works.

**Comment by adamesque** [comment]
I'm having what looks like the same issue using testem 0.8.3 (via ember-cli). Node 0.12.2 on Mac OS X 10.10.3.

Also: if I start up testem in an empty directory, pressing `q` does not quit; the testem UI disappears and then I have to Ctrl-C to exit. If I run `testem ci` in an empty directory, it hangs, but Ctrl-C doesn't help; I get stuck in an infinite loop:

```
> testem ci

1..0
# tests 0
# pass  0
# fail  0

# ok
^Cnot ok 1 Error
    ---
        message: >
            Received SIGINT signal
    ...

1..1
# tests 1
# pass  0
# fail  1
^Cnot ok 2 Error
    ---
        message: >
            Received SIGINT signal
    ...

1..2
# tests 2
# pass  0
# fail  2
``` 

Some ember-cli users also seem to see an issue like this (see the most recent comments on https://github.com/ember-cli/ember-cli/issues/1083).

**Comment by adamesque** [comment]
Oh — one last thing: if I pass the `-p` option to `testem ci` with something other than the default port, the ci run completes with no problems. `testem ci -p 7358` works fine.

**Comment by adamesque** [comment]
When I run `testem ci -d` without the port assignment, I get the following log:
```
info Test'em starting...
info Seeking for config file...
info Starting ci
info Starting server
info Process PhantomJS already killed.
info spawning: /usr/local/lib/node_modules/phantomjs/lib/phantom/bin/phantomjs - ["/usr/local/lib/node_modules/testem/assets/phantom.js","http://localhost:7357/3947"]
info New client connected: PhantomJS 1.9 3947
info Browser PhantomJS finished all tests.
info Process PhantomJS terminated. null 'SIGTERM'
```

With the port assignment, I don't see the `SIGTERM`:

```
info Test'em starting...
info Seeking for config file...
info Starting ci
info Starting server
info Process PhantomJS already killed.
info spawning: /usr/local/lib/node_modules/phantomjs/lib/phantom/bin/phantomjs - ["/usr/local/lib/node_modules/testem/assets/phantom.js","http://localhost:7358/6394"]
info New client connected: PhantomJS 1.9 6394
info Browser PhantomJS finished all tests.
```

**Comment by adamesque** [comment]
Just downgraded to testem v0.8.2, and the issue is gone.

**Comment by sbalko** [comment]
I could confirm that problem (invoking Chrome in my case) - explicitly assigning a different port does the trick.

**Comment by cdaringe** [comment]
i changed the port in my testem.json file, and indeed, the issue vanished. thanks for the tip @adamesque , @sbalko

**Comment by ronelliott** [comment]
I was also having this issue while running in dev, changing the port fixed the issue. I'm on OS X (10.10), not sure if that has anything to do with it. thanks for the tips @adamesque

**Comment by cdaringe** [comment]
thanks @johanneswuerbach.  unfortunately, #616 doesn't seem to resolve the issue for me.  i asserted that it was all up to date, and that any global installation was purged.  the port hack doesn't seem to do the trick either.  do you see any potential reasons why it would still hang?

**Comment by OrKoN** [comment]
I believe I experience the same problem. Node 4.2.2, Phantomjs 1.9.8, Ubuntu 14.04. Here is a travis CI log https://travis-ci.org/OrKoN/simple-jspm-project/builds/91923564 and the test repo for it https://github.com/OrKoN/simple-jspm-project

**Comment by OrKoN** [comment]
I think I found what's causing the problem in my case: if there are some errors (e.g. parsing errors), testem ci will not exit. The solution is to fix all problem in the code (e.g. arrow functions or use of Promises that are not supported in the phantomjs).

Probably, testem does not detect if some errors happened in the phantomjs.

**Comment by johanneswuerbach** [comment]
The issue is that you are loading your src before loading testem, which makes the browser error, before testem had any chance to instrument it. Testem v1 provides now a way to load `testem.js` first and manually hook it into your test framework when it has been loaded:
https://github.com/testem/testem/blob/master/examples/qunit_lazy/test.html
