### ISSUE TITLE
Feature: Visualise skipped tests

### ISSUE THREAD

**Issue by amk221** [testem/testem#611]
It would be great if skipped tests were displayed in the output.

(In much the same was as QUnit does..)
![screen shot 2015-07-27 at 15 42 15](https://cloud.githubusercontent.com/assets/382061/8908820/182cb8bc-3476-11e5-81c1-ffe6de5f8420.png)

Either by a different colour, or by a count at the end of the suite.

**Comment by osherx** [comment]
+1
