### ISSUE TITLE
bug: before_tests hook runs twice in dev mode

### ISSUE THREAD

**Issue by osherx** [testem/testem#631]
scenario
---
- use the following `testem.yml`:

```
before_tests: echo "BEFORE" >> flow.txt
after_tests: echo "AFTER `time`" >> flow.txt
```
- run testem in dev mode
- quit testem
- check the content of `flow.txt`

expect:
---

```
BEFORE
AFTER

```

found
---

```
BEFORE
BEFORE
AFTER

```

**Note: ** the bug is not reproduced in CI mode

**Comment by paulot** [comment]
This doesn't seem to affect the latest version of testem.
