### ISSUE TITLE
Liberal globbing can cause parse errors by treating directories listings as scripts

### ISSUE THREAD

**Issue by searls** [testem/testem#640]
So if I have a glob for `src_files` like so:

``` json
"src_files": [
    "vendor/**/*",
    "lib/**/*",
    "test/helpers/**/*",
    "test/**/*"
  ]
```

This will generate a script tag for the directory itself like this: `<script src="lib/examples">`, which will include the HTML:

``` html
<h1>Files In This Directory</h1>
<ul>
<li><a href="math.js">math.js</a></li>
</ul>
```

And cause a console error, which sometimes fails a test run.

## Steps to Reproduce

I'm using Node v4.0.0 and npm 2.14.2. I'm on OS X 10.10.5.

1. Clone: https://github.com/testdouble/jasmine-example
2. `git checkout cfde63891afd0be0b6483e64b6547ed749790c89`
3. `npm start`
4. Open Chrome console

What you'll see is the error "Uncaught SyntaxError: Unexpected token <", for a supposed source file named "examples:1". This is not a file, but when you click through, it's clearly an HTML directory listing of that `lib/examples` directory that is somehow being generated and included in the runner.

Here's a screenshot:

<img width="1162" alt="screen shot 2015-09-20 at 17 27 52" src="https://cloud.githubusercontent.com/assets/79303/9982993/f59ae400-5fbc-11e5-8762-371e30587ec3.png">

Any thoughts?

**Comment by johanneswuerbach** [comment]
Great catch, I think a sensible default would be to serve only .js files when watching globbing dirs , but still allow to serve non .js files when explicitly specified.

**Comment by johanneswuerbach** [comment]
Hey, you can actually use `/**/*.js` to get only js files. https://github.com/testem/testem#configuration-file
