### ISSUE TITLE
what is the right way to configure working with a test server on the background?

### ISSUE THREAD

**Issue by osherx** [testem/testem#642]
Hi 

We're a full-stack developers team, and we work a lot with xhr, jsonp, ajax and stuff like that.
For this, we need to cover tests of data-sending over the network - at least to a test server

For this - we need a test server running in parallel to testem - and sometimes even as a part of it

As architect I want to facilitate for my developers the handling of this test server through testem, so I'm looking for a setup in which testem will make sure the test server runs before the tests are run, and close it if no open tab is executing.

currently, before_tests and after_tests run a command that expects to exit.
The dirty way would be to start some process, save the PID in a file, and kill it after - but that's dirty...
Another way would be to start the server in background once on start, and kill it on_exit, but that still does not sound elegant.

testem is a node project. why shouldn't I be able to 'plug in' some express app, and have testem manage it, watch it and restart it when it changes?

Here's the full use cases list:
---
**As** a Node + H5 full stack developer
**I want** testem to accept via configuration an http server module, keep have it running as long as the test continues, and terminate it when tests stop
**so that** I can focus on coding instead of operating services

**As** a Node + H5 full stack developer
**I want** testem to watch provided server and restart the tests when it changes automatically
**so that** I can focus on coding instead of operating services

**As** a Node + H5 full stack CORS developer
**I want** the provided server to run on a different port
**so that** I can emulate CORS calls as demandingly as possible

**As** a Node + H5 full stack NON-CORS developer
**I want** to be able to configure the provided server to run as part of the server that provides the test page
**so that** I take CORS out of the equation

thoughts? directions? advises? 
PR is considerable if I get some help about how to fit into the project.
If we could trust testem on this - it would be so coool.... :)

**Comment by johanneswuerbach** [comment]
Hi @osherx,

thanks for your detailed writeup. As a middleware kind of structure could work, I don't think it will provide you enough value in the long run to jump through all the hops and limitations. (limited to the express version of testem, conflicting dependencies, etc.) and is worth the complexity integrated in testem.

The most common setup I have seen nowadays is to have another tool coordinating your server / databases / caches together with your "frontend app" like docker compose, foreman, etc. Especially with micro service style architectures. 

When you prefer not to have another tool running converting your app into a start & stoppable service could also be another solution as you already mentioned.

Another solution could be to start testem programatically from your server:
https://github.com/airportyh/testem/blob/master/testem.js#L84
