### ISSUE TITLE
Introduction to Testem at Global Ember Meetup

### ISSUE THREAD

**Issue by taras** [testem/testem#658]
EmberCLI uses Testem to run tests. Testem just works, so many people don't really think about it. The setup is fairly transparent to the users. There might be more advanced techniques that most users are not aware of. 

Would someone who's very knowledgable with Testem be open to coming on to [Global Ember Meetup](http://global-ember-meetup.com) to share some less known "Tips and Tricks" for working with Testem? 

Global Ember Meetup is an online meetup with presentations done via screen sharing. We have an "Ember Testing Day" coming up in 2 weeks and we have an opening for this kind of talk.

What do you think?

**Comment by airportyh** [comment]
@taras thank you for the invite. @johanneswuerbach and I did consider doing this, but alas neither of us can. I wish you a great event!
