### ISSUE TITLE
Running testem along other toolchain elements in the same shell

### ISSUE THREAD

**Issue by ArnaudRinquin** [testem/testem#679]
I can't figure out a way to run `testem` along other tools such as `webpack` in watch mode using the same `npm script` using [`concurrently`](https://github.com/kimmobrunfeldt/concurrently) such as:

```
{
  "scripts": {
    "dev": "concurrent 'webpack -w' 'testem'"
  }
}
```

Problem is that `testem` and its tab based UI is not really keen on sharing the same terminal.

The server mode doesn't really replace dev mode as it does output anything and won't open browsers.

Is there a way to have the features of dev mode while "sharing" the terminal?

**Comment by johanneswuerbach** [comment]
Hello, I think the easiest way would be to use a terminal multiplexer like tmux or an orchestration tool like docker compose. 

You could also use pure testem like this: https://github.com/testem/testem/pull/683/files, but thiswon't display any `webpack -w` output.

**Comment by johanneswuerbach** [comment]
Add another testem example https://github.com/testem/testem/pull/684, improvements welcome!

**Comment by ArnaudRinquin** [comment]
Thanks for your answer. Unfortunately, having the test runner dependent of the packager (`webpack` or ...) is something we absolutely want to avoid.

We are looking at writing a reporter that will just output in `stdout` similar to what `karma` does.

**Comment by johanneswuerbach** [comment]
Sure, I'm currently in the middle of refactoring testem to easily allow changing reporters also in dev https://github.com/testem/testem/pull/664
