### ISSUE TITLE
question: custom test page with tape

### ISSUE THREAD

**Issue by cdaringe** [testem/testem#682]
Hi all:

I'm trying to use testem on a pretty example page I already have running.  I was hoping something like this would work:

```html
<!-- myfolder/test.mustache -->
        {{#serve_files}}
        <script src="/{{src}}"></script>
        {{/serve_files}}
        <script src="/testem.js"></script>
    </body>
</html>
```

```js
// built and served by testem (webpack'd)
var test = window.tape = require('tape');
setTimeout(function() {
    test('constructor', function(t) {
        t.pass('yahoo');
        t.end();
    });
}, 500);
```

In this regard, `tape` is on the window, and I was hoping `testem.js` would pick it up.

<img width="381" alt="screen shot 2015-11-19 at 10 38 12 pm" src="https://cloud.githubusercontent.com/assets/1003261/11292681/a3fe3116-8f0e-11e5-9a00-f3a6eb4d6860.png">

Tips?

Thanks!

**Comment by airportyh** [comment]
Testem doesn't actually interact with tape directly. Instead it reads the texts printed by tape in the console, and uses a TAP parser to interpret it. See this [configuration](https://github.com/testem/testem/blob/master/examples/tape_example/testem.json).

**Comment by cdaringe** [comment]
If you look at the screenshot, however, you'll notice that the output is
not parsed.  The README says when using a test_page that framework and
src_files options are ignored.  I use a configuration like the one you've
linked to in many of my other projects.  This is the first time that I'm
trying to integrate with an existing test_page.

Thanks!

On Friday, November 20, 2015, Toby Ho <notifications@github.com> wrote:

> Testem doesn't actually interact with tape directly. Instead it reads the
> texts printed by tape in the console, and uses a TAP parser to interpret
> it. See this configuration
> <https://github.com/testem/testem/blob/master/examples/tape_example/testem.json>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/testem/testem/issues/682#issuecomment-158371270>.
>


-- 
Chris Dieringer
p: (503)358-8577
e: cdieringer@mrn.org
w: http://cdaringe.com

**Comment by johanneswuerbach** [comment]
Could you post your testem config?

**Comment by cdaringe** [comment]
gladly!

```json
{
    "test_page": "examples/index.mustache",
    "serve_files": [
        "test.bundle.js"
    ],
    "before_tests": "webpack --config webpack.testem.config.js",
    "launch_in_dev": ["PhantomJS", "Chrome"]
}
```

where `webpack.testem.config.js` =>
```js
...
    entry: { 'test': './test/index.js' },
    output: {
       ...
        filename: '[name].bundle.js', // generates test.bundle.js, which testem is serving
    },
};
```

**Comment by johanneswuerbach** [comment]
Thanks for the config, the following setup works for me:

`testem.json`:
```
{
    "framework": "tap",
    "test_page": "test.mustache",
    "serve_files": [
        "test-bundle.js"
    ],
    "before_tests": "webpack --config webpack.testem.config.js",
    "launch_in_dev": ["PhantomJS", "Chrome"]
}
```
`test.mustache`:
```
<html>
<body>
  <script src="/testem.js"></script>
  <script>
  Testem.handleConsoleMessage = function(msg){
    Testem.emit('tap', msg)
    return false
  }
  </script>
  {{#serve_files}}
  <script src="/{{src}}"></script>
  {{/serve_files}}
  </body>
</html>
```

**Comment by johanneswuerbach** [comment]
Add the full example, improvements welcome!

**Comment by cdaringe** [comment]
Thanks guys! :)
