### ISSUE TITLE
Print stdout and stderr when a browser exits unexpectedly

### ISSUE THREAD

**Issue by cotsog** [testem/testem#694]
Some Travis CI users are currently seeing PhantomJS browser exiting unexpectedly e.g. the following error message is printed:

    not ok 334 PhantomJS - Browser "phantomjs /home/travis/build/org/repo/node_modules/ember-cli/node_modules/testem/assets/phantom.js http://localhost:7357/7638" exited unexpectedly.

Hence I think it would be helpful to print the browser's stdout and stderr content to try to understand what is going on.

I think this is where the change should be made:

https://github.com/testem/testem/blob/28aaa2707369b289c48a64ff12e5c26287321058/lib/runners/browser_test_runner.js#L169

Thanks in advance for your help and let me know if you need more information.

**Comment by bobisjan** [comment]
Hi,

I've just encountered this when running `ember test` with freshly updated application with Ember 2.2.0 and Ember Data 2.2.1.

In my case problem occurs on server with Ubuntu, tests running locally on Mac are passing (both using Phantom 2.0).

**Comment by johanneswuerbach** [comment]
This is support since `v1.7.0`
