### ISSUE TITLE
Multiple, parallel instances of same launcher?

### ISSUE THREAD

**Issue by trentmwillis** [testem/testem#732]
I know it's possible to run parallel instances of _different_ launchers, but is there any way currently to run parallel instances of the _same_ runner? As a bonus, can you run multiple instances with different URLs? I attempted this through various config options but it doesn't seem supported currently.

Specifically, I'm looking to parallelize tests during CI by batching tests across multiple instances of Phantom. Something along the lines of running `/tests?batch=1` on one instance and `/tests?batch=2` on another instance.

**Comment by Vanuan** [comment]
Oh, so parallel option is only for different launchers?
Yeah, sounds obvious, since there's only one html file.

**Comment by trentmwillis** [comment]
@johanneswuerbach just noticed you added a "feature" label to this. I'll see if I can implement something, but I want to discuss the API before beginning work.

I think this should be broken into two features:

1. run parallel instances of the same runner, and
2. run instances with multiple test pages

I tend to think for (1) that this should just be the default if a value greater than `1` is specified for the `parallel` option but only 1 launcher is defined. Unless we want multiple launchers all with multiple instances, in which case I think we should introduce a new config option. I tend to think the second might be the more correct solution, but I'm unsure what that configuration API would look like.

For (2), maybe we define a new config option, `parallel_test_pages` or repurpose the existing `test_page` option such that an array of test page strings get mapped to the launcher instances. Would need a behavior for if the number of test pages doesn't match the number of instances (I tend to think we should opt to using the number of test pages in those cases).

**Comment by johanneswuerbach** [comment]
I really like the array of test pages idea :+1:

The `parallel` setting currently allows you to control your launchers like the following:
* `-1`: All launchers are run in parallel
* `x < launchers`: Launcher runs are pooled and will never exceed `x`, this is important for platforms like saucelabs were you are only allowed to run a limited number of jobs in parallel.
* `x > launchers`: Just runs everything in parallel

I think cleanest way would be to implement running an array of test pages with your defined launchers respecting the defined parallel setting. WDYT?

**Comment by trentmwillis** [comment]
Just to make sure I'm understanding, this means we would essentially use the array of test pages to determine whether multiple instances of a single launcher are run, correct?

So if I had:

```
{
  "test_page": [
    "/tests?batch=1",
    "/tests?batch=2"
  ],
  "launch_in_ci": [
    "PhantomJS"
  ],
  "parallel": -1
}
```

I would get 2 instances of PhantomJS, the first would run `/tests?batch=1` and the second with `/tests?batch=2`? This would mean that the number runs is essentially `(# launchers) * (# test pages)`.

If that's what you're suggesting, seems good to me.

**Comment by johanneswuerbach** [comment]
Yes, exactly.

And just to be 100% sure, this should run then two batches with 2 instances of phantomjs.
```
{
  "test_page": [
    "/tests?batch=1",
    "/tests?batch=2",
    "/tests?batch=3",
    "/tests?batch=4"
  ],
  "launch_in_ci": [
    "PhantomJS"
  ],
  "parallel": 2
}
```

**Comment by trentmwillis** [comment]
:+1: sounds good. Will try to work on this sometime soon.

**Comment by alexindigo** [comment]
Did I understand correct that `?batch=N` is not something required by `testem`, but something for tests suite to differentiate on, correct?

So if I want to run same tests in parallel,  I could do like this:

```
{
  "test_page": [
    "/my_test_page",
    "/my_test_page",
    "/my_test_page",
    "/my_test_page"
  ],
  "launch_in_ci": [
    "PhantomJS"
  ],
  "parallel": 4
}
```

**Comment by trentmwillis** [comment]
@alexindigo yeah, it's not a required thing, just an example. The test pages could be whatever you want.

**Comment by alexindigo** [comment]
Cool. Thanks for the clarification.

**Comment by Vanuan** [comment]
How would it split tests into batches? Would it hook into mocha's .only tests?

**Comment by Vanuan** [comment]
Ok, I think I got it. You propose to write different tests into different html pages, right?

**Comment by stefanpenner** [comment]
@Vanuan i believe adding segmentation support to the test runners is perfectly reasonable.

**Comment by Vanuan** [comment]
Yeah. I mean, if a given test runner (e.g. [parallel-mocha](https://github.com/atsuya/parallel-mocha)) supports parallelism, why should we use such a hack as multiple test pages, we should be able to reuse the same page using ".only" or something like that.

**Comment by johanneswuerbach** [comment]
I think there has been a little misunderstanding, test page means in this case (testem config) a relative url, which can be either `A.html` & `B.html` or `A.html?batch=1` & `A.html?batch=2`.

While auto-parallelizing sounds like an interesting idea, I don't think its in the scope of V1 of this feature and something which should be added later. Having multiple "pages" already allows you to easily split your tests into groups with just specifying different `?grep=` url parameters when you use mocha.

The approach https://github.com/atsuya/parallel-mocha takes (just splitting the tests into groups by number) is from my experience in most cases not really what you want as with a lot of fast and a few slow tests one worker is usually mostly idling. A more interesting approach would be to feed the runtime information of a previous run (from a xunit file for example) back into the system and allow it to build more balanced groups like for example circleci does https://circleci.com/docs/setting-up-parallelism
