### ISSUE TITLE
skipped tests printed as failures

### ISSUE THREAD

**Issue by avdv** [testem/testem#737]
We're using ember-cli and today version 1.13.15 was released which depends on testem ^1.0.0.

Now, when running `ember test` all tests which should be skipped with `QUnit.skip` show up as failures:

```
$ ember test -f 'xyz' --launch firefox
...
1..17
# tests 17
# pass  12
# skip  0
# fail  5
```

But when running using `ember test -f 'xyz' --launch firefox --serve` the CUI displays no errors and in the browser the relevant tests show up as "skipped".

**Comment by avdv** [comment]
I think I found the problem: https://github.com/testem/testem/blob/master/lib/runners/browser_test_runner.js#L126

Adding

```js
  skipped: result.skipped
```

to the object passed as the second parameter makes it work again.

**Comment by johanneswuerbach** [comment]
Thanks, mind sending a PR?

**Comment by avdv** [comment]
Sure thing ;-)

Do you have any pointers as to where I should best put the test?

**Comment by johanneswuerbach** [comment]
I guess the easiest would be here: https://github.com/testem/testem/blob/master/tests/runners/browser_test_runner_tests.js#L61-L84 The existing tests seems not to cover your case properly.
