### ISSUE TITLE
Process is not killed properly when running tests from command line

### ISSUE THREAD

**Issue by vedharish** [testem/testem#739]
To reproduce this issue, have a look at this [gist](https://gist.github.com/vedharish/c664d7cad6ecd28926aa).

The gist has 3 files - 
1. test.js - This js files writes its own process pid in 'test.log' and has a timeout to wait for the actual test.
2. testem.json - Regular testem.json file to launch test.js in ci mode
3. testem_log_pid.patch - Basically, its purpose is to log the pid of the process testem is trying to kill. Just add the console.log line at the appropriate line in launcher.js in testem repo or just git-apply this patch on the master branch.

Now, run testem from command line in debug mode - `testem ci -d`
Monitor the logs - `tail -f test.log testem.log`
Open the url mentioned in `test.log` from a regular browser.

Expected - The testem page should load and the ci test should exit properly
Issue - The process pid mentioned in test.log (logged from test.js) and the process testem is trying to kill (logged from launcher.js) are different on some systems.
In test.log, we get a line like - `started with pid 20004` and we can see something like `Trying to kill process with pid 20003 with Signal SIGTERM` on the console.

Due to this issue, tests which catch `SIGTERM, SIGINT, exit` events cannot quit properly.
I tried this on mac - `El Capitan node 0.10+` - works fine
It showed the issue (different pids) on - `ubuntu/vivid64` vagrant machine with node `v0.10.41` and same machine with node `v4.2.4` with nvm`

**Comment by vedharish** [comment]
Might be related to nodejs/node#4432 ?

**Comment by hbrysiewicz** [comment]
This is happening for me when running from CircleCI. Here are the deats on CircleCI's environment
```
Architecture: x86_64
Username: ubuntu
Ubuntu 12.04 (precise)
Kernel version: 3.2
git 1.8.5.6
gcc 4.6
g++ 4.6
GNU make 3.81
```

**Comment by hbrysiewicz** [comment]
Ok, so I was able to ssh into the CircleCI box and get X11 forwarded to test out your gist. I do see a different process in test.log from the one testem is trying to kill.

![output](https://s3.amazonaws.com/f.cl.ly/items/2u3f2P0h0P1o3r0z0L1h/Screen%20Shot%202016-01-22%20at%203.14.45%20PM.png?v=1a66c0ee)

**Comment by johanneswuerbach** [comment]
Hey, could you try using `exe` instead of `cmd`. `cmd` is using [child_process.exec](https://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback), while `exe` is using [child_process.spawn](https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options).

Usage example:
https://github.com/testem/testem/blob/master/examples/saucelabs/testem.json#L13-L17

**Comment by vedharish** [comment]
Using `exe` works for me
