### ISSUE TITLE
Skipped tests are reported as failures in 1.0.0

### ISSUE THREAD

**Issue by alexlafroscia** [testem/testem#740]
I have a bunch of QUnit tests that are using the `skip` feature to ignore the test.  On older versions of Testem, they would be reported as passing, but instead they are reported as failures now :frowning:

Confusingly, it only seems to be an issue when running in a `testem ci` environment; if I run the tests normally, they all are reported as passing.

**Comment by johanneswuerbach** [comment]
This should be resolved in `1.0.1`. Could you verify that upgrading to that version fixes the issue for you?

**Comment by alexlafroscia** [comment]
There still seems to be something wrong; while the skips _are_ being reported correctly now, `testem` finished with a non-`0` exit code that makes CI think that the tests failed.

**Comment by alexlafroscia** [comment]
Thanks for taking care of this!
