### ISSUE TITLE
Regression introduced in abb0fdcf2

### ISSUE THREAD

**Issue by avdv** [testem/testem#749]
In commit abb0fdcf2 the reporter logic was changed in regard to what a "passed" check is, that means now any tests which don't test anything (yet) fail:

```
// QUnit
test('it renders', function(assert) {
    assert.expect(0);
}
```

Output

```
not ok 1 Firefox 43.0 - Integration | Component | assets/card asset: it renders
```

Before that change, the logic was that the test passed, if it didn't fail and it wasn't skipped.

Now (https://github.com/testem/testem/blob/abb0fdcf2c6c84405999b632c9eda8a34076852e/lib/runners/browser_test_runner.js#L95), the value of `result.passed` must be truthy as well.

In my case it is not, as it's a number value actually, which is `0`:

```
{
  "id":1,
  "name":"Integration | Component | assets/card asset: it renders",
  "items":[],
  "failed":0,
  "passed":0,
  "skipped":false,
  "total":0,
  "runDuration":2052
}
```

I suppose that the QUnit adapter should not pass the number of passed checks, but simply a boolean value for `passed`?

Here's the check I wrote for bisecting which produces the failure:
```
    it('counts a test as passed when no failures occurred', function() {
      runner.onTestResult({
        "name": 'no checks',
        "items": [],
        "failed": 0,
        "passed": 0,
        "skipped": false,
        "total":0,
        "runDuration": 20
      });
      expect(reporter.pass).to.equal(1);
    });
```

I can fix it using this (ugly) code without breaking existing tests:

```diff
--- a/lib/runners/browser_test_runner.js
+++ b/lib/runners/browser_test_runner.js
@@ -87,7 +87,7 @@ BrowserTestRunner.prototype = {
       });
 
     this.reporter.report(this.browser, {
-      passed: result.passed && !result.failed && !result.skipped,
+      passed: (result.passed !== false) && !result.failed && !result.skipped,
       name: result.name,
       skipped: result.skipped,
       runDuration: result.runDuration,
```

**Comment by johanneswuerbach** [comment]
Thanks for that detailed issue :bow: I guess I'll have to look through all the reporters again and double check what they emit.

You code looks like a great hot fix, mind sending a PR?

**Comment by avdv** [comment]
Sure, PR submitted (#751)
