### ISSUE TITLE
Testem hard crash with 1.1.2

### ISSUE THREAD

**Issue by seawatts** [testem/testem#763]
Ever since the release of `1.1.2` I have been seeing the following error.
I am using testem with `ember test --server`
It looks like `ember-cli` has a version of `^1.0.0` which would resolve to `1.1.2`
https://github.com/ember-cli/ember-cli/blob/v2.3.0-beta.1/package.json#L116

When I run this command everything works fine the first time around. However, if I change a file it will try to reload testem and it crashes with the following error. Because it hard crashes phantomjs and chrome are still running in the background as zombie processes... =/ 

```
var failedItems = test.get('items').filter(function(item) {
                                     ^
TypeError: Cannot read property 'filter' of undefined
    at failedTestDisplay (./node_modules/testem/lib/reporters/dev/split_log_panel.js:46:38)
```

I went in there and debugged the issue. When the tests reloaded the second time it looks like the `test` object had a message on it saying that it had `unexpectedly lost connection to chrome`

Here are all my versions I'm running
```
ember-cli: 2.3.0-beta.1
ember-cli-qunit: 1.2.1
ember: 2.3.0
chrome: 48.0.2564.82 beta (64-bit)
phantomjs: 2.1.1
OS X El Capitan 10.11.2
```

testem.json
```
{
  "framework": "qunit",
  "test_page": "tests/index.html?hidepassed",
  "disable_watching": true,
  "launch_in_ci": [
    "PhantomJS"
  ],
  "launch_in_dev": [
    "PhantomJS",
    "Chrome"
  ]
}
```

Let me know if you need anymore context to debug this issue.

**Comment by musaffa** [comment]
Confirmed. It crushes with a fresh installation of an ember app.
