### ISSUE TITLE
dbus-launch with chromium via xfvb does not launch

### ISSUE THREAD

**Issue by aortbals** [testem/testem#772]
When upgrading from [ember-cli#v2.2.0-beta.1](https://github.com/ember-cli/ember-cli/releases/tag/v2.3.0-beta.1) to [ember-cli#v2.3.0-beta.1](https://github.com/ember-cli/ember-cli/releases/tag/v2.3.0-beta.1), testem was upgraded from `0.9.11` to `1.1.3` (resolved from `^1.0.0`). This includes the [dbus-launch changes](https://github.com/testem/testem/pull/689). This causes the following error when running testem with [chromium](https://launchpad.net/ubuntu/trusty/+source/chromium-browser) on Ubuntu 14.04 via jenkins and xvfb.

```
Built project successfully. Stored in "XXX".
not ok 1 Browser "dbus-launch --exit-with-session chromium,chromium-browser --user-data-dir=/tmp/testem.chromium --no-default-browser-check --no-first-run --ignore-certificate-errors http://localhost:8371/7540" exited unexpectedly with exit code 1.

1..1
# tests 1
# pass  0
# skip  0
# fail  1
Xvfb stopping
```

I was not able to find a solution with the current version, I reverted the upgrade which fixed this issue.

**Comment by johanneswuerbach** [comment]
Sorry, I'm going to revert this change.

**Comment by aortbals** [comment]
Thank you @johanneswuerbach!

**Comment by johanneswuerbach** [comment]
Released in `v1.2.1`

**Comment by davidhao3300** [comment]
Rather than completely reverting the change, can we not set this line to only Chrome? https://github.com/testem/testem/pull/776/files#diff-f6055c71cdaa57eff4423a9403d5b00bL252

**Comment by johanneswuerbach** [comment]
Yes, we could do that, but I would like to have a regression test for this this time.

**Comment by davidhao3300** [comment]
I can do that, can you point me to where the integration tests are located?

**Comment by johanneswuerbach** [comment]
Also it seems a bit weird to have this workaround in testem itself, shouldn't the script executing testem have this instead? Its making a lot of assumptions of the environment that browser is running in.

Integration tests are here: https://github.com/testem/testem/blob/master/tests/ci/ci_tests.js Travis might have chrome installed, but I'm not sure.

**Comment by davidhao3300** [comment]
Yeah I agree, I'm not sure where else to put this workaround for now though; Chrome developers have decided to put the workaround in their own test scripts as well =_=. Finding the issue/workaround took a lot of time/effort that I don't want others to have to go through, and it involves duplicating a lot of Testem's Chrome browser config.

Ignoring the part about Karma, this looks like a guide to setting up Chromium on Travis: http://swizec.com/blog/how-to-run-javascript-tests-in-chrome-on-travis/swizec/6647

**Comment by johanneswuerbach** [comment]
On the other side @aortbals is using chromium, which should also be problematic as its a chromium https://code.google.com/p/chromium/issues/detail?id=309093 bug, this workaround breaks him, so I guess we would either detect that issue differently or move it out of testem launchers and into a `before_test` or something.

**Comment by davidhao3300** [comment]
We do differentiate between Chrome and Chromium, so wrapping only Chrome and not Chromium should be ok

**Comment by johanneswuerbach** [comment]
But shouldn't that bug also occure on chromium? Before this will be reintroduced we should also check why this hack failed for aortbals so I wont break others again. After re-reading the chromium issue I still think this hack shouldn't be the default launcher for linux but instead documentend and just executed as part of a ci run before running testem. Wdyt?

**Comment by davidhao3300** [comment]
Haven't experienced it on Chrome myself, and we should be on the most recent version of Chrome/Testem

**Comment by davidhao3300** [comment]
Well, the main reason why I introduced this workaround is because Chrome consistently hangs for us on our Linux machines, didn't realize it affected Testem's tests as well lol. We can also introduce this as a flag that's by default off if it turns out this affects users differently for whatever reason.

**Comment by aortbals** [comment]
The version of Chromium I had this issue on:

```
$ dpkg -l chromium-browser
||/ Name                     Version           Architecture      Description
+++-========================-=================-=================-=====================================================
ii  chromium-browser         48.0.2564.82-0ubu amd64             Chromium web browser, open-source version of Chrome
```

We test a lot of applications using chromium + xvfb + jenkins on 64-bit Ubuntu 14.04 and have never had an issue that required a workaround like wrapping in `dbus-launch`.

**Comment by davidhao3300** [comment]
Alright, I'll take a deeper look tonight/tomorrow. We also use Xvfb + jenkins on 64-bit Ubuntu 14.04, but we use google-chrome instead.

**Comment by davidhao3300** [comment]
I'm reading the dev forum you linked and just realized this is one I originally found lol. If you look at https://code.google.com/p/chromium/issues/detail?id=309093#c85, the comment indicates that glib is causing issues. Could you run the command `ldd --version` on your Jenkins machine? I want to see if a version difference is causing the discrepancy in issues

**Comment by aortbals** [comment]
```
$ ldd --version
ldd (Ubuntu EGLIBC 2.19-0ubuntu6.6) 2.19
...
```

**Comment by davidhao3300** [comment]
glib versions are the same
Google Chrome version:
```google-chrome-stable        47.0.2526.106-1    amd64              The web browser from Google```
Looks like we are out of date by 1 major version, I'll try to upgrade today and see if that changes anything.

**Comment by davidhao3300** [comment]
Upgrading Chrome to 48.0.2564.97-1 didn't change anything. Testem is returning "{browser} exited unexpectedly with exit code 1", which is different from before where it just hung. I'll look into this more.

**Comment by davidhao3300** [comment]
Fixed the exiting problem, Chrome hanging still affects me without dbus-launch (aka using the latest version of Testem).
I haven't seen any issues about Chrome failing, so perhaps the solution is to just wrap only Chrome in dbus-launch.
