### ISSUE TITLE
`testem` command isn't reporting `before_tests` error.

### ISSUE THREAD

**Issue by m59peacemaker** [testem/testem#783]
I've created a repo that demonstrates the issue. https://github.com/m59peacemaker/issue-testem-before_tests

The js file has a syntax error, so browserify will fail.
`before_tests` runs browserify and fails and the testem interface just hangs rather than reporting an error.

**Comment by Vanuan** [comment]
Would be great to output command results to console.log

**Comment by rupurt** [comment]
@Vanuan that would be fantastic.
