### ISSUE TITLE
typo in mocha example

### ISSUE THREAD

**Issue by yonida** [testem/testem#787]
In the following two examples there is a typo in mocha.css path

https://github.com/testem/testem/blob/e893e9a4dbc9369387fb69c8e4def40e9b64d908/views/mochachairunner.mustache

https://github.com/testem/testem/blob/e893e9a4dbc9369387fb69c8e4def40e9b64d908/views/mocharunner.mustache

`<link rel="stylesheet" href="//cdjs.cloudflare.com/ajax/libs/mocha/2.3.4/mocha.css">`
should be
`<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/mocha/2.3.4/mocha.css">`

**Comment by johanneswuerbach** [comment]
Good catch, mind sending a PR?

**Comment by yonida** [comment]
sure

**Comment by yonida** [comment]
looks like it is already fixed on master. should I close this one?
