### ISSUE TITLE
Xunit report should not include name attribute on failure nodes

### ISSUE THREAD

**Issue by jreading** [testem/testem#791]
I'm still having trouble getting Jenkins to parse the xunit report generated by testem. 

I've found [this validator](http://www.freeformatter.com/xml-validator-xsd.html) that fails on the name attribute on the failure element. This is by using [this XSD] (https://svn.jenkins-ci.org/trunk/hudson/dtkit/dtkit-format/dtkit-junit-model/src/main/resources/com/thalesgroup/dtkit/junit/model/xsd/junit-4.xsd) and my report from testem. I can't find any xunit reports that have that attribute.

The name attribute is on the the parent `testcase` element and seems both invalid and redundant. Are you ok with a PR to remove this?

**Comment by johanneswuerbach** [comment]
Yes, a PR sounds great.

**Comment by Vanuan** [comment]
Having the same problem

**Comment by jreading** [comment]
FYI, Jenkins Junit reader happy now!

**Comment by johanneswuerbach** [comment]
Thanks, released as `v1.4.0`

**Comment by Vanuan** [comment]
Looks like Jenkins still split test results into "Phantom 1" and "9". A different problem?
