### ISSUE TITLE
Documentation for remote selenium

### ISSUE THREAD

**Issue by Vanuan** [testem/testem#796]
Don't see any example how to use testem with a remote browser (Selenium hub/Sauce Labs/BrowserStack). Is it even supported?

**Comment by johanneswuerbach** [comment]
You mean?
https://github.com/testem/testem/tree/master/examples/saucelabs
Or
https://github.com/testem/testem/tree/master/examples/browserstack

Anything further you were looking for?

**Comment by Vanuan** [comment]
It looks like both are creating a tcp socket somehow to the real webdriver.
Is is possible to do this with Selenium Hub? I suppose some additional gem can be written.

**Comment by Vanuan** [comment]
Found this: https://github.com/akiellor/testem-selenium-launcher/blob/master/bin/selenium-launcher
Looks like it is what I'm looking for.
