### ISSUE TITLE
Provide PhantomJS path

### ISSUE THREAD

**Issue by olivierlesnicki** [testem/testem#797]
Say phantomjs is not globally installed on my system. Is there a way I can configure the path?
Say `./node_modules/.bin/phantomjs`

**Comment by johanneswuerbach** [comment]
When you project is using https://github.com/Medium/phantomjs, testem should fine the local installation of phantomjs automagically. Otherwise `phantomjs` needs to be in your `$PATH`.

**Comment by alexindigo** [comment]
@olivierlesnicki if you run testem via npm-scripts you have your `./node_modules/.bin` in the PATH and testem would pick up your local copy of phantomjs.

**Comment by olivierlesnicki** [comment]
good call!
