### ISSUE TITLE
Add ability to pass flags to browser

### ISSUE THREAD

**Issue by vine77** [testem/testem#808]
It [looks like](https://github.com/testem/testem/blob/v1.4.1/lib/browser_launcher.js#L133) the command line arguments used for browsers are hard-coded. It would be nice to, for example, be able to pass the forthcoming [`--auto-open-devtools-for-tabs`](https://bugs.chromium.org/p/chromium/issues/detail?id=410958) to launch Chrome with DevTools opened.

**Comment by trentmwillis** [comment]
Seems like it should be possible to concat custom args within the [`getArgs` function](https://github.com/testem/testem/blob/master/lib/launcher.js#L124-L134) to get this support. Would need to define an api for passing in those custom arguments, but after that I feel like it could be relatively straightforward.

**Comment by vogdb** [comment]
Is there a way to achieve this now? I need to launch Chrome with flags `--use-fake-device-for-media-stream --use-fake-ui-for-media-stream` in order to test WebRTC.

**Comment by vogdb** [comment]
@trentmwillis can you please give me a bit more details on how to implement it. I may give it a try. This feature seems very attractive to me. It will solve my problems.

**Comment by vine77** [comment]
Perhaps we could add a `chrome_args` config option, like the [`phantomjs_args`](https://github.com/testem/testem/blob/v1.9.1/lib/utils/known-browsers.js#L145) option @ef4 added in #560.
 
@vogdb, in the meantime, maybe you could try to:
- Specify a new custom Chrome launcher in testem.json ([example](https://github.com/testem/testem/blob/v1.9.1/examples/saucelabs/testem.json#L13)); or
- Add Chrome arguments, which have moved to [known-browsers.js#L22-L33](https://github.com/testem/testem/blob/v1.9.1/lib/utils/known-browsers.js#L22-L33), in a fork

**Comment by vogdb** [comment]
Ok, thanks! If find time, I would definitely try. For now I'm using karma. Need to deliver my work in time :-\
