### ISSUE TITLE
node_example doesn't work

### ISSUE THREAD

**Issue by gavruk** [testem/testem#809]
`examples/node_example`

When I run `npm test` (`"test": "node ../../testem.js ci -P 10 --launch node --" `), I see:

```
1..0
# tests 0
# pass  0
# skip  0
# fail  0

# ok
```
To make it work, I need to update `testem.json`
from
```
"Node": {
  "command": "mocha tests.js",
  "protocol": "tap"
}
````
to
```
"Node": {
  "command": "mocha tests.js -R tap",
  "protocol": "tap"
}
````

But when I run `node ../../testem.js --launch node --`, I see:
![347592c8e3](https://cloud.githubusercontent.com/assets/507195/13398633/424a5a1a-df10-11e5-9e47-fba296b88e8d.jpg)

This means example is not working. The issue happens when I run my own tests. How to fix this?

Log:
```
info Test'em starting..
info Seeking for config file...
info Starting dev
info Starting server
info Node
info runnerAdded
info Start triggered test run.
info Process Node already killed.
info Running tests...
info cmd: mocha tests.js -R tap
info ok 1 hello says hello world

info ok 2 hello says hello to person

WARN Node closed 0
info Process Node terminated. 0 null
info Got keyboard Quit command
info Stopping dev
info Process Node already killed.
```

**Comment by alexindigo** [comment]
@johanneswuerbach Looks like this one bites us again: https://github.com/testem/testem/pull/748#discussion_r50686463

**Comment by johanneswuerbach** [comment]
Yes, that example should have only:

```
"Node": {
  "command": "mocha tests.js",
}
```

as only the exit code is verified in this case. Will look how the messaging inside testem can be improved in this case.

**Comment by gavruk** [comment]
@johanneswuerbach this way also doesn't work
![df866d603b](https://cloud.githubusercontent.com/assets/507195/13401918/0f1a074e-df1f-11e5-8b10-1c1f862c23ee.jpg)

**Comment by alexindigo** [comment]
@johanneswuerbach Just to have better understanding, it supposed to execute tests on file, right?

**Comment by johanneswuerbach** [comment]
There a basically three modes in testem for launchers:

a) `none`: launch a process and wait until it exited, then mark it as passed (exit code 0) or failed (any other exit code)
b) `tap`: Used when the process prints parseable tap output to have more details and mark the tests passed / failed from the parsed output
c) `browser`: When the process is a browser

Basically a) should always work and b) when the process prints tap, dunno why a) wasn't and will check that when I have time.

**Comment by alexindigo** [comment]
So `mocha` has to output `tap` in order to get proper reporting?
And by default it goes with spec of something, correct?

**Comment by gavruk** [comment]
@alexindigo correct. Mocha is `-R tap` to output in tap format

**Comment by alexindigo** [comment]
Funny, it just happened that I'm using `tap` everywhere, and was under impression that testem supports other formats as well. :)

**Comment by juwalter** [comment]
Hi there, anyone up for it? I put it on bounty source

https://www.bountysource.com/issues/31444340-node_example-doesn-t-work

**Comment by alexindigo** [comment]
@juwalter It would nice to understand what is desired outcome. So far it's not clear.
@johanneswuerbach Do you have any specific path in mind? Last time we've talked about it I've got impressions you're happy with the thing.

**Comment by gavruk** [comment]
@alexindigo the desired outcome is to make test result to be shown like this

![](https://raw.githubusercontent.com/testem/testem/master/images/green.png)

using the custom `mocha` command

**Comment by johanneswuerbach** [comment]
The course of action I see here is to remove this line https://github.com/testem/testem/blob/master/examples/node_example/testem.json#L5 and fix that it report looks like
```
1..0
# tests 1
# pass 1
# skip  0
# fail  0

# ok
```

or in the UI as @gavruk posted.

**Comment by juwalter** [comment]
I agree w/ @johanneswuerbach 

actually, both outputs should be possible, depending on how you prefer the reporting of test results

**Comment by johanneswuerbach** [comment]
Which it actually does for me:
```
$ npm install
npm WARN deprecated graceful-fs@2.0.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
mocha@2.4.5 node_modules/mocha
├── escape-string-regexp@1.0.2
├── commander@2.3.0
├── diff@1.4.0
├── supports-color@1.2.0
├── growl@1.8.1
├── jade@0.26.3 (commander@0.6.1, mkdirp@0.3.0)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── debug@2.2.0 (ms@0.7.1)
└── glob@3.2.3 (inherits@2.0.1, graceful-fs@2.0.3, minimatch@0.2.14)
$ npm test

> @ test examples/node_example
> node ../../testem.js ci -P 10 --launch node --

ok 1 Node - Node
    ---
        Log: |
            { type: 'log',
              text: '\n\n  hello\n\r    ✓ says hello world\n\r    ✓ says hello to person\n\n\n  2 passing (7ms)\n\n' }
    ...

1..1
# tests 1
# pass  1
# skip  0
# fail  0

# ok
```

Mind posting OS / Node version @gavruk ?

**Comment by gavruk** [comment]
@alexindigo `testem ci` works great. But the issue is when you run `testem` in TDD mode (without `ci`)
node 5.3, OS X 10.11.3

**Comment by johanneswuerbach** [comment]
https://github.com/testem/testem/pull/810 should fix your issues.

**Comment by juwalter** [comment]
@gavruk can you please confirm?

**Comment by gavruk** [comment]
Not sure if this is related, but with the following config
```
{
  "watch_files": [
    "./lib/*",
    "./lib/**/*",
    "./tests/*",
    "./tests/**/*"
  ],
  "launchers": {
    "Node1": {
      "command": "mocha -R tap tests/* tests/**/*",
      "protocol": "tap"
    },
    "Node2": {
      "command": "mocha -R tap tests/* tests/**/*",
      "protocol": "tap"
    }
  },
  "launch_in_dev": [ "Node1", "Node2" ],
  "launch_in_ci": [ "Node1", "Node2" ]
}
```
when I run `../../testem.js`, all tests haven't been ran, and then ran again immediately.

And If I click enter multiple times (re-run tests), I see
`(node) warning: possible EventEmitter memory leak detected. 11 processError listeners added. Use emitter.setMaxListeners() to increase limit.` and process exits

**Comment by johanneswuerbach** [comment]
Not really related, could you open another issue for that?
