### ISSUE TITLE
maxDepth in public/testem/decycle.js

### ISSUE THREAD

**Issue by choclaudio** [testem/testem#811]
the payload depth has increased by one but the maxDepth in decycle.js has not reflected this change.
This has the implication that message/stack in errors fall outside of the maxDepth.

Bumbing up maxDepth to 5 (from 4) in decycle.js  solves the issue.

**Comment by bantic** [comment]
Probably related to https://github.com/testem/testem/pull/792.
Can you explain how to view/confirm this error so that I can confirm the fix?

**Comment by choclaudio** [comment]
Hi @bantic, fast response, cool :+1: 

In my case I can create an empty Ember(2.3+) project (uses testem) and just run the tests with any reporter or even just with the --server flag.

so on a vanilla Ember project running
ember-test
ember test --server (look the console output not the web-output)
ember test --reporter teamcity

used to produce the error message and stack trace, but it no longer does.

By bumping up maxDepth in decycle by one the issue is solved, but I do not know if this is the correct place to fix the bug.

**Comment by choclaudio** [comment]
@bantic it might be good if I clarify that I am breaking jshint rules on purpuse to produce a failed test.
