### ISSUE TITLE
Can no longer set custom reporter in testem.js

### ISSUE THREAD

**Issue by dbushong** [testem/testem#821]
As of https://github.com/testem/testem/commit/1ea331eaa192b737722ec8154d8839f6e56d2d03 you can no longer configure a custom `reporter` in `testem.js`:

The priority of `fileOptions` is lower than that of `progOptions`, and `progOptions` has a default for `-R` (`tap`), thus no matter what you put in `testem.js` for `reporter`, it never gets used.

**Comment by johanneswuerbach** [comment]
What is defaulting `progOptions` to `tap`? Are you using testem standalone or with `ember-cli`?

**Comment by dbushong** [comment]
https://github.com/testem/testem/blob/master/testem.js#L36 standalone

**Comment by gwenaelp** [comment]
I have this issue too. If you unset the default option in https://github.com/testem/testem/blob/master/testem.js#L36, it works like a charm.

Any plans to handle this upstream?

**Comment by johanneswuerbach** [comment]
Sure, PRs welcome. I'll have a look as soon as I have time.

**Comment by DerivcoHK** [comment]
It is because the "getConfigProperty" function of "Config" will return the progOptions first rather than that of fileOptions. 

```
Config.prototype.getConfigProperty = function (key) {
  ....
  if (key in this.progOptions && typeof this.progOptions[key] !== 'undefined') {
    return this.progOptions[key];
  }

  if (key in this.fileOptions&& typeof this.fileOptions[key] !== 'undefined') {
    return this.fileOptions[key];
  }
  .....
}
```

So when we unset the default option in https://github.com/testem/testem/blob/master/testem.js#L36, it works.

**Comment by johanneswuerbach** [comment]
Fixed by https://github.com/testem/testem/pull/860
