### ISSUE TITLE
"-1" Broken for Parallel Option

### ISSUE THREAD

**Issue by trentmwillis** [testem/testem#830]
It seems like with `1.5.0` the option to use "-1" for `parallel` has been broken. It doesn't run any browsers for me. Thought it might be my local project but tested on master and am seeing the same behavior. Will try to investigate more tomorrow if I have time.

**Comment by trentmwillis** [comment]
This turned out to be a user error. I was using `"-1"` instead of `-1`, so when it checks the value ([here](https://github.com/testem/testem/blob/master/lib/app.js#L351)), it evaluates it as not equaling `-1`.

This behavior works properly for other strings (e.g., `"2"`), since they are obviously not equal to `-1`. Would it be okay to improve this check to catch the string case as well? Otherwise the behavior can seem inconsistent (it did for me at least). We could loosen the check up to using `!=` or explicitly check `parallel !== '-1'` as well. Thoughts?

**Comment by johanneswuerbach** [comment]
No definitely open to match the string too. Seems like a trivial, but annoying mistake.

**Comment by trentmwillis** [comment]
Sounds good, will have a PR ready soon.
