### ISSUE TITLE
Running one browser at a time (parallel 0)

### ISSUE THREAD

**Issue by bcardarella** [testem/testem#835]
I'd like to force the browsers to wait for one to finish before another start, no concurrent browsers running.

Use case: We like to avoid mocking/stubbing in our client app test suites. We'll run an actual test server to prove out full integration between front end and back end. This however presents a problem when the client is expecting the server to be in a particular data state per test. We'll send data setup/teardown commands for each test.

I've tried `parallel: 0` but this doesn't prevent more than one browser running at a time. Thoughts?

**Comment by johanneswuerbach** [comment]
Parallel `1` should do run parallel browser at any given time.

**Comment by bcardarella** [comment]
@johanneswuerbach I tried `1` (which I believe is the default) but I'm seeing Chrome start up before Phantom has finished

**Comment by johanneswuerbach** [comment]
Are you running in `dev` or `ci` mode?

**Comment by bcardarella** [comment]
I am not certain, I am running through ember-cli. I can look into what mode that runs

**Comment by bcardarella** [comment]
I believe that ember-cli is using the CI move: https://github.com/ember-cli/ember-cli/blob/master/lib/tasks/test.js#L17

**Comment by johanneswuerbach** [comment]
Could you share your testem config?

**Comment by montogeek** [comment]
I am running it with `testem ci -P 1` it waits for the browser to close to start with the next one

**Comment by johanneswuerbach** [comment]
@bcardarella do you still see this issue?

**Comment by bcardarella** [comment]
@johanneswuerbach we actually found another solution, parallel sandboxed DB transactions server-side 😄
