### ISSUE TITLE
Choose any free port automatically

### ISSUE THREAD

**Issue by Vanuan** [testem/testem#842]
It would be great if there was a mode in which testem would choose any free port from a specific range.

Use case is testem in ci mode. It's incomplete without an ability to run multiple builds simultaneously on one machine.

**Comment by Vanuan** [comment]
Or at least create a dedicated return code for "listen EADDRINUSE" error.

**Comment by johanneswuerbach** [comment]
You can already select `port: 0` in your testem config to use a random port. https://github.com/testem/testem/blob/master/tests/ci/ci_tests.js#L46

**Comment by Vanuan** [comment]
Ok, thanks.
