### ISSUE TITLE
Errors loading testem.js with Safari 9.0.3...

### ISSUE THREAD

**Issue by the-t-in-rtf** [testem/testem#847]
I see intermittent browser errors loading the testem scripts themselves, but only in Safari:

```
not ok 26 Safari 9.0 - global failure
    ---
        stack: >
            http://localhost:7357/testem.js:931
        message: >
            SyntaxError: JSON Parse error: Unexpected identifier "object"
        Log: |
```

It appears to be a JSON parsing error:

```
deserializeMessage: function(message) {
    return JSON.parse(message);
},
```

This happens intermittently, sometimes all tests pass, and the tests that report browser errors vary from run to run.

**Comment by bantic** [comment]
@the-t-in-rtf Any more details that you can share about the structure/content of your tests? That error indicates that `message` is already an object (rather than a string of JSON), but I'm not sure why that would be the case.
