### ISSUE TITLE
nativeParseInt is not a function

### ISSUE THREAD

**Issue by screendriver** [testem/testem#850]
My code to test uses some [lodash](https://lodash.com) functions like [_.parseInt()](https://lodash.com/docs#parseInt). In Test'em they throw following error

``` js
TypeError: nativeParseInt is not a function
    at parseInt (http://localhost:7357/565/src/jspm_packages/npm/lodash@4.10.0/parseInt.js:47:10)
```

When I **don't** use Test'em (e.g. a mocha HTML page hostet with [broswer-sync](https://www.browsersync.io/)) the error disappears.

Does somebody has any idea what's going on here?

**Comment by johanneswuerbach** [comment]
Do you do any transpiling usually before running your tests? Looks like testem is shipping the raw sources.

**Comment by screendriver** [comment]
Yes. I am using [jspm](http://jspm.io), [SystemJS](https://github.com/systemjs/systemjs) and ES2015 with the [Babel](https://babeljs.io) transpiler.
