### ISSUE TITLE
Add `--disable-save-password-bubble` for Chrome

### ISSUE THREAD

**Issue by wagenet** [testem/testem#861]
This should disable password save prompts in Chrome. According to http://peter.sh/experiments/chromium-command-line-switches/ it only works on Macs. If this sounds good, I can PR.

**Comment by johanneswuerbach** [comment]
Sounds good to me!

**Comment by johanneswuerbach** [comment]
Testem `v1.11.0` allows to not customise arguments passed to custom launchers: https://github.com/testem/testem#customizing-browser-arguments
