### ISSUE TITLE
Passing Metadata from Test to Reporter

### ISSUE THREAD

**Issue by tjni** [testem/testem#863]
I would like to collect some information from my running tests and surface them to my custom reporter. What I'm looking for is something similar to logs, except something that allows objects through, possibly with a category or type (as a string) to allow more structured filtering.

The flow I am thinking of is: adapter emits a new type of event, test runner collects it and passes it along to the reporter. Open to other ideas as well.

Willing to work on a PR if there ends up being agreement that this is the right direction and approach.

**Comment by johanneswuerbach** [comment]
> The flow I am thinking of is: adapter emits a new type of event, test runner collects it and passes it along to the reporter. Open to other ideas as well.

Sounds like an interesting idea, PR welcome!
