### ISSUE TITLE
Tests nondeterministically stop running

### ISSUE THREAD

**Issue by davidhao3300** [testem/testem#867]
We've had instances where tests just stop running in the middle since 2 months ago. Unsure if this is a Testem bug (still investigating), but wanted to post this here in case others have experienced the issue.

I found that it happens more often in our Jenkins CI tests than when running CI tests locally, but we've managed to see it once locally (didn't manage to get any useful info at the time since it was someone else's computer).

The error typically manifests itself as "Browser ... disconnected unexpectedly", but browser itself isn't crashing or anything (no errors in the chrome debug logs). The socket times out due to "ping timeout"

**Comment by davidhao3300** [comment]
Some more details: We're running QUnit tests on Chrome 50.0.2661.94 on Linux. Testem version is 1.6.0

**Comment by davidhao3300** [comment]
I think we figured out that our code is causing the problem

**Comment by xamoom-pali** [comment]
@davidhao3300 Can you be more specific what the problem was? We are facing a similar issue
