### ISSUE TITLE
Ember tests not connecting with v1.7.0 of testem in place

### ISSUE THREAD

**Issue by eddiesholl** [testem/testem#868]
The ember-cli package has a dependency on testem ^1.3.0. My CI build starting failing to run 'ember test ci' today, and it seems to be because of a fresh npm install which dragged in 1.7.0 instead of 1.6.0. The error message coming out is like:

phantomjs <...>/node_modules/ember-cli/node_modules/testem/assets/phantom.js http://localhost:36360/9518/tests/index.html?hidepassed" failed to connect. testem.js not loaded?

I have confirmed that getting version 1.6.0 installed as a dependency of ember-cli gets things back up and running, and tests are completing now.

I'm not sure if this is going to be on the testem or ember side of things, posting here for now.

**Comment by johanneswuerbach** [comment]
What version of phantomjs are you running? Which Node and OS versions are you using?

**Comment by eddiesholl** [comment]
Sorry should have included that:

PhantomJS: 2.1.7 (not phantom-prebuilt)
npm: 3.3.12
node: 5.5.0
ember-cli: 2.4.1
OS: Ubuntu 15.10

**Comment by johanneswuerbach** [comment]
Could you share the path phantomjs is installed in?

**Comment by eddiesholl** [comment]
The full path to phantom.js is /var/lib/jenkins/workspace/refresh develop build/node_modules/ember-cli/node_modules/testem/assets/phantom.js, its part of a jenkins job.

Interestingly, phantomjs is not actually on the path for the build user, I assume 'ember test' does some tricks to locate it. There's a phantomjs binary at ./node_modules/.bin/phantomjs and ./node_modules/phantomjs/bin/phantomjs

I have tried installing phantomjs-prebuilt and tried running it with testem 1.7.0, same issue.

**Comment by johanneswuerbach** [comment]
Sounds like this https://github.com/testem/testem/pull/857 broke it, testem is no longer manually looking into your modules but instead prepending `./node_modules/.bin` to the`PATH` and then just executing the binary. Could you check what `./node_modules/.bin/phantomjs -v` prints?

**Comment by eddiesholl** [comment]
An npm install -g of either phantomjs or phantomjs-prebuilt fixes things. It seems just getting it on the path is the solution.

That diff you linked has this for linux:
-        supported: findableByWhichOrModule
+        supported: findableByWhich

Might be nice if something was printed out if the 'which' strategy is going to fail, but apart from that its a configuration issue at my end.

**Comment by tuhintshukla** [comment]
I am running into similar issue in my environment:-

ember-cli: 2.5.0
node: 4.2.1
os: linux x64
testem --version
1.7.0
phantomjs -v
2.1.1

I have phantomjs and phantomjs-prebuilt installed globally and I am running the tests on CI server which is a centos 6.7 using:-
ember test ci --server /ember test ci --server

Any resolutions/workarounds ?

**Comment by johanneswuerbach** [comment]
Could you share the output of `which phantomjs`?

**Comment by tuhintshukla** [comment]
[satest@:~]$ which phantomjs
/usr/bin/phantomjs
[satest@:~]$

**Comment by tuhintshukla** [comment]
@johanneswuerbach Thanks a lot for the fix, but looks like I am still having the issue in my environment. Not sure whats going on, When I use DEBUG=* I can see the thread just hangs . Should I file it as a separate issue ?

**Comment by johanneswuerbach** [comment]
Yes, please :+1:
