### ISSUE TITLE
Testing for document.readyState

### ISSUE THREAD

**Issue by Cmdv** [testem/testem#875]
Hi I'm trying to test that `readyState` is being waited for in a function I have.

This is my helper function that delays adding all elements to the DOM
```
function createDelayedRenderTarget (id = null) {
  let element = document.createElement('div');
  element.className = 'cycletest';
  if (id) {
    element.id = id;
  }
  setTimeout(() => {
    document.body.appendChild(element);
  }, 400)
  return element;
}
```

Then I'm just doing a notStrictEqual against `readyState, "complete"`

Is there a way of doing this as the readyState always seems to be complete?

**Comment by johanneswuerbach** [comment]
Usually that depends on the test framework as most of them only run your tests after the document readyState is complete

**Comment by Cmdv** [comment]
ah ok so I best look into the Mocha docs, thank you feel free to close 😄
