### ISSUE TITLE
PhantomJS viewportSize customization

### ISSUE THREAD

**Issue by williamsbdev** [testem/testem#876]
I just recently upgraded PhantomJS from 1.9.8 to 2.1.1 and noticed that several tests were failing in a work project because the viewportSize changed from 400x300 to 1024x768. I much prefer the more reasonable window size with the upgrade, however we had several tests that were relying on the smaller size for our media queries (wrong of us to do without being able to specify window size).

I've see that there was an attempt at some configuration for being able to set this #398 but it was declined in favor of a fixed size that is unchangeable by the user #415.

Would it be possible to allow user defined viewportSize? Is there some middle ground where something more along the lines of the #398 PR would be accepted?

Thanks!

**Comment by johanneswuerbach** [comment]
I agree with @airportyh and instead of additional PhantomJS specific options, I would prefer a way to provide custom args for included lunchers. The config for your issue might look like:

```
"launchers": {
  "PhantomJS-400x300": {
    "extend": "PhantomJS",
    "args": ["viewport-size", "400x300"]
  }
}
```

Sadly I didn't had time to spike an implementation yet, but if you beat me on that I would be very welcome.

**Comment by johanneswuerbach** [comment]
Testem `v1.11.0` allows now to customise arguments passed to build-in launchers: https://github.com/testem/testem#customizing-browser-arguments
