### ISSUE TITLE
Istanbul + Mocha + Coverage report

### ISSUE THREAD

**Issue by hadida** [testem/testem#894]
Hi All,

 I have got problem to generate coverage report using Istanbul + Mocha + Coverage report. My simple solution based on native examlpes mocha_lazy and coverage_istanbul. Unfortunately I always got coverage*.json empty. I debug and found that variable `window.__coverage__` is undefined. 
Example coverage_istanbul work marvelous. 

Could you advice ?

**Comment by psdao1102** [comment]
You havent instrumented your code. Unfortunatly instrumenting methods can very wildly so youll just have to do some googling.

**Comment by johanneswuerbach** [comment]
You can also find an example here: https://github.com/testem/testem/tree/master/examples/coverage_istanbul
