### ISSUE TITLE
Specifying `report_file` option is not working in 1.9.0

### ISSUE THREAD

**Issue by rwjblue** [testem/testem#900]
I suspect https://github.com/testem/testem/commit/b97b9c290f31608256bedbe0d67fb5b328ae6b2b is to blame, but I am not certain (haven't bisected).

The config I am using is:

```js
module.exports = {
  framework: 'qunit',
  test_page: 'tests/index.html?hidepassed',
  disable_watching: true,
  host: 'localhost.twitch.tv',
  launch_in_ci: [ 'PhantomJS' ],
  launch_in_dev: [],
  xunit_intermediate_output: true
  report_file: 'test-results/data.xml',
  reporter: 'xunit'
};
```

**Comment by rwjblue** [comment]
There is also a failure in ember-cli's test suite, but I am unsure if it is the same issue (I don't recall ember-cli using `report_file` directly).

**Comment by alexgraul** [comment]
We're seeing the same issue - an empty report_file being created.

**Comment by johanneswuerbach** [comment]
Sorry, I rolled `v1.9.0` back and re-published `v1.8.1` as `v1.9.1`. Feel free to upgrade until this has been resolved.

**Comment by adhamhf** [comment]
@johanneswuerbach can you verify that's published?

`npm install testem@1.9.1 `

is failing:

`No compatible version found: testem@1.9.1`

**Comment by johanneswuerbach** [comment]
Yes and https://www.npmjs.com/package/testem agrees. Do you use a registry mirror or cache? Sometimes those are slower.

**Comment by hemp** [comment]
My workaround yesterday was to pin testem to 1.8.1 and I dug back into why this morning and saw this issue was filed.

Thanks for 1.9.1.  It is working for our ember-cli based builds and the report file has data.

**Comment by tjni** [comment]
Hi Johannes, do you need any help on this issue? I have a vested interest in seeing 1.9.0 out, so I'm happy to spend some time this weekend working on this.

**Comment by johanneswuerbach** [comment]
Sure, I haven't really had time to investigate what exactly is broken on master for this and the ember cli test suite.

For the suite is seems just to be an issue with changed output, but I need to dig deeper.

**Comment by johanneswuerbach** [comment]
Release the first 1.10 rc. Would really appreciate if somebody could test it in their apps.

**Comment by john-kurkowski** [comment]
Sorry I didn't get a chance to try it out first. I see 1.10.0 and 1.10.1 have been released. Our CI has been passing! 🎉
