### ISSUE TITLE
Jenkins CI: 'testem' is not recognised as an internal or external command.

### ISSUE THREAD

**Issue by vytch** [testem/testem#91]
Hi

I tried to set up a CI server following the youtube video 'Testem CI' on Windows7.
I have installed GIT.
I have installed the tap plugin.
I have installed node and testem.

When I am in the workspace I can execute : testem launchers and I get the browsers that I have installed on my OS.

However when I trigger a built from Jenkins, it says that 'testem' is not recognised as an internal or external command.

Is there any additional steps I need to do to complete the installation?

Thanks

Vytch

**Comment by ahmet571** [comment]
IF NEWMAN or another EXE is not starting from JENKINS CHANGE the USER of JENKINS to jour SELF: (user who wants to execute Jenkins job!!!).

![newman issue on windows](https://cloud.githubusercontent.com/assets/5954380/22287819/958ec86c-e2f4-11e6-8fce-b71e8dd9a1e8.png)

**Comment by humiimalik** [comment]
@ahmet571  Hi, what user did you use? it doesnt list the user with i login in the system.
It shows the admin and administrator but doesnt accept the passwords. any other way?
