### ISSUE TITLE
Testem process exits (times out?) after 10s with code 1, no error

### ISSUE THREAD

**Issue by adamyonk** [testem/testem#923]
It seems to happen when my webpack process takes longer than 10s to build, I have this in my config:
```
{
  "framework": "tap",
  "launch_in_dev": ["PhantomJS"],
  "launch_in_ci": ["PhantomJS"],
  "src_files": ["tests/bundle.js"],
  "serve_files": ["tests/bundle.js"],
  "on_start": {
    "command": "npm run build:test:watch",
    "wait_for_text": "[built]"
  },
  "on_exit": {
    "command": "rm tests/bundle.js"
  }
}
```
The build:test:watch script basically does `webpack --define process.env.NODE_ENV='\"test\"' tests/index.js tests/bundle.js --watch`

Is there some timeout in testem that will kill the process if it doesn't see the `wait_for_text` after 10s?

**Comment by adamyonk** [comment]
Could this be a bluebird promise timing out?

**Comment by johanneswuerbach** [comment]
Sorry, I didn't had time investigating, what testem, node, OS versions are you using?

**Comment by adamyonk** [comment]
node v6.2.0, macOS 10.12 (also happened on 10.11), testem 1.10.0-0

**Comment by stefanpenner** [comment]
I was pointed to this issue, If I'm reading this correctly I may have just fixed it: https://github.com/testem/testem/pull/925

**Comment by adamyonk** [comment]
Hm… It still seems broken to me. Here's an asciinema of what I'm seeing: https://asciinema.org/a/2q8x4ahkubbxbjgkz3ep2j8xj

**Comment by adamyonk** [comment]
I thought maybe it was this, https://github.com/testem/testem/blob/7a89cabdb20741e7801f8eeb3a0c7e3cbea0b869/lib/hook_runner.js#L39, but increasing it to 20 or 30s doesn't seem to help things.

**Comment by adamyonk** [comment]
Occasionally I can get the webpack build to happen in ~9-9.5 seconds, and only then, testem will NOT crash, and will correctly watch my webpac bundle.

**Comment by adamyonk** [comment]
Updated the original issue to include my whole config file.

**Comment by stefanpenner** [comment]
ah, ya that seems like a different case then what my pr resolved.

**Comment by tjni** [comment]
I attempted to reproduce this using sleeps in the on_start command but wasn't able to get this to fail silently without a timeout message showing up. @adamyonk, do you see the same symptoms when some other long running command is used instead of your build?

**Comment by adamyonk** [comment]
Yeah:
```
{
  "framework": "tap",
  "launch_in_dev": ["PhantomJS"],
  "launch_in_ci": ["PhantomJS"],
  "src_files": ["tests/bundle.js"],
  "serve_files": ["tests/bundle.js"],
  "on_start": {
    "command": "sleep 5; echo '[built]'",
    "wait_for_text": "[built]"
  },
  "on_exit": {
    "command": "rm tests/bundle.js"
  }
}
```
works, but
```
{
  "framework": "tap",
  "launch_in_dev": ["PhantomJS"],
  "launch_in_ci": ["PhantomJS"],
  "src_files": ["tests/bundle.js"],
  "serve_files": ["tests/bundle.js"],
  "on_start": {
    "command": "sleep 10; echo '[built]'",
    "wait_for_text": "[built]"
  },
  "on_exit": {
    "command": "rm tests/bundle.js"
  }
}
```
doesn't.

**Comment by johanneswuerbach** [comment]
Looks like we are setting a default timeout of 10s https://github.com/testem/testem/blob/master/lib/hook_runner.js#L39 for the hook to be executed when a text is provided.

While I'm also open to remove this default, you should be able to tweak this by setting `wait_for_text_timeout` to a higher number.

**Comment by adamyonk** [comment]
Hm, I'm not sure if that's it either now. Here's a what's happening when I run the tests: https://asciinema.org/a/buqircp9dbb4qbhv6oe92s5bx (the bottom pane is a tail of the testem.log)

**Comment by johanneswuerbach** [comment]
Released in `1.10.2`

**Comment by adamyonk** [comment]
Thanks for the work on this! It seems to be running more reliably now. I think I am occasionally still hitting the `waitForTextTimeout` - am I correct in assuming this is the config setting to change it?
```
{
  "hook": {
    "wait_for_text_timeout": 30000
  }
}
```

**Comment by johanneswuerbach** [comment]
👍

**Comment by adamyonk** [comment]
This just won't die! On testem 1.10.2 with the following config:
```
{
  "hook": {
    "wait_for_text_timeout": 60000
  }
}
```

I'm still seeing it crash quite often with this at the end of the testem log:
```
…
info ok 118 should have only exclude condition for less inclusive wildcard

info Browser PhantomJS finished all tests. undefined
info PhantomJS 2.1 onEnd
WARN PhantomJS closed 1
info Process PhantomJS terminated. 1 null
```
