### ISSUE TITLE
Why doesn't the SauceLabs example show an example of findElement?

### ISSUE THREAD

**Issue by djangofan** [testem/testem#932]
Why doesn't the SauceLabs example show an example of findElement(el)  or  .get(url) ?  All it has is a testem file with a hello true/false assertion.  That doesn't prove anything that would occur in a web-browser.  Am I missing something here or am I correctly noticing a lack of a good example here?

https://github.com/testem/testem/tree/master/examples/saucelabs

**Comment by johanneswuerbach** [comment]
The example currently shows how to run http://jasmine.github.io/ tests on saucelabs a qunit example could be found here https://github.com/emberjs/ember.js/blob/master/testem.dist.json

`findElement` sounds more like you would like to use selenium directly, which should be possible, I just never needed it.

suacie itself uses wd https://github.com/johanneswuerbach/saucie/blob/master/lib/launch.js#L33, but just to navigate to the testem url, so nothing really advanced.

**Comment by djangofan** [comment]
Thanks for the reply.  I come from a Java/Selenium testing point of view.  Are you suggesting that I would be able to get a handle on the browsers Javascript executor (not using Selenium) and perform actions (in the browser that was started on SauceLabs)?     If so, do you have once such simple example of doing that?  Or, can you point me to one?   For example, I want to navigate the page in my QUnit test and I want the SauceLabs video to show that navigation.

**Comment by johanneswuerbach** [comment]
Due to how testem works (iframe injected into the test page) page navigation isn't possible as this would kill the communication channel between the tests and the testem server.

The only way I could imaging running selenium tests with testem is to create a separate process, which prints tap output https://testanything.org/ to stdout parsed by testem, but you wouldn't really need testem for doing that. You can find an example how to do that here: https://github.com/testem/testem/tree/master/examples/node_tap_example

Generally most web-frameworks I have seen stub any real page navigation in test mode.

**Comment by djangofan** [comment]
Ok, this is starting to make sense now (and I am not saying that I wanted to run in SauceLabs, but you should understand why I thought that way, from my background in Java/Selenium/Sauce).  Correct me if I am wrong, as this was not obvious from the existing documentation:

# I am noticing that SauceLabs shows an additional TAB where the results of a test run are shown, presumably from the iframe-runner you mentioned.  
# Grunt must be uploading a test.json up to SauceLabs so it can be executed up there?  If this is true, I need to locate the code that does this (client side) so that I can understand how it works.
# Navigating in the browser, would refresh the DOM and break any tests that had been injected into the page.
# Grunt+QUnit/TestEm is only really meant for unit tests, not acceptance tests or browser actions.   There are other frameworks for the alternative, such as Casper, right?
# To run Javascript tests in Sauce, I should allow Sauce to open any given browser to an exact URL and execute all tests (without causing page navigation of the browser).  Therefore, SauceLabs videos+screenshots are not useful and should be disabled.

**Comment by johanneswuerbach** [comment]
> Grunt+QUnit/TestEm is only really meant for unit tests, not acceptance tests or browser actions. There are other frameworks for the alternative, such as Casper or Slimer, right?

Yes, testem is mostly used for running javascript tests with a stubbed or fake backend. How extensive you are able to do that really depends on your frontend stack, emberjs for example also allows extensive acceptance testing https://guides.emberjs.com/v2.6.0/testing/acceptance/

> Navigating in the browser, would refresh the DOM and break any tests that had been injected into the page.

Correct, while changing the dom isn't an issue, unloading the iframe is.

> 1, 2, 5

Most of the logic is handled inside https://github.com/johanneswuerbach/saucie, which works like a browser. It uses https://wiki.saucelabs.com/display/DOCS/Setting+Up+Sauce+Connect to forward you localhost to sauce and then uses webdriver / selenium to open the page and run your tests. Once all tests have been executed it injects some scripts into the browser to extract the results and updates the SauceLabs jobs details, which renders the test details tab.

If videos+screenshots are useful for you really depends on your frontend stack, ember for example shows a small iframe showing your current app state.

**Comment by djangofan** [comment]
Thanks, yes, I am using Ember.js .  Thanks for your help.
