### ISSUE TITLE
Has Testem been used with Angular 2

### ISSUE THREAD

**Issue by RodrigoMattosoSilveira** [testem/testem#939]
I have been using Testem for a while now, I like it. Im migrating my dev framework from Angular 1 to Angular 2. I'm trying to avoid investing too much time figuring out how to set up Testem in Angular 2. I would love to hear from some one who has done it!

Thanks in advance for your assistance

Regards 
Rodrigo

**Comment by johanneswuerbach** [comment]
Nothing should prevent testem to work with angular 2.
