### ISSUE TITLE
Testem hanging with Firefox in Jenkins...

### ISSUE THREAD

**Issue by adhamhf** [testem/testem#953]
I'm not sure how to debug this and could use some help.  In our Jenkins setup we launch npm test which runs ember test via xvfb-run:  xvfb-run ember test --reporter xunit.

At this point it appears the testum tries to launch Firefox, but times out waiting for Firefox.

 I would like to enable debug mode for testum but it appears this is only an option if you run testem via the command line directly.   I think it's likely this is all a problem in our CI system but I simply don't know how to get more information.

Any thoughts?

**Comment by adhamhf** [comment]
@rwjblue @johanneswuerbach  any thoughts on this?  Its blocking our automated testing of firefox.  Below are the last few log lines where I launched xvfb-run with -x and had node logging set to debug.  It does actually like like some tests are running but there a socket.io:client timeout that appears to hang the test.  I've left it running like this for an hour and it never recovers.

```
        Mon, 22 Aug 2016 13:44:28 GMT socket.io-parser decoded 2["tests-start"] as {"type":2,"nsp":"/","data":["tests-start"]}
        Mon, 22 Aug 2016 13:44:28 GMT socket.io:socket got packet {"type":2,"nsp":"/","data":["tests-start"]}
        Mon, 22 Aug 2016 13:44:28 GMT socket.io:socket emitting event ["tests-start"]
        Mon, 22 Aug 2016 13:44:39 GMT engine:ws received "42["warn","detachable==false modals are not accessible"]"
        Mon, 22 Aug 2016 13:44:39 GMT engine:socket packet
        Mon, 22 Aug 2016 13:44:39 GMT socket.io-parser decoded 2["warn","detachable==false modals are not accessible"] as {"type":2,"nsp":"/","data":["warn","detachable==false modals are not accessible"]}
        Mon, 22 Aug 2016 13:44:39 GMT socket.io:socket got packet {"type":2,"nsp":"/","data":["warn","detachable==false modals are not accessible"]}
        Mon, 22 Aug 2016 13:44:39 GMT socket.io:socket emitting event ["warn","detachable==false modals are not accessible"]
        Mon, 22 Aug 2016 13:46:04 GMT engine:ws closing
        Mon, 22 Aug 2016 13:46:04 GMT socket.io:client client close with reason ping timeout
        Mon, 22 Aug 2016 13:46:04 GMT socket.io:socket closing socket - reason ping timeout
```

**Comment by adhamhf** [comment]
If I fire up FF in a full X11 session I get warnings about unresponsive scripts.  I *think* this is what is happening in the xvfb session, so I'm going to try and figure out how to headless disable this warning.  BTW, FF runs our tests twice as slow as phantom, chrome or safari so it seems like this is the cause.

**Comment by johanneswuerbach** [comment]
@adhamhf sorry for the late reply, were you able to get it running?

**Comment by adhamhf** [comment]
@johanneswuerbach yup, still seeing it.  Part of the problem is the dom.max_script_run_time preference in Firefox.  If something takes longer than 3 seconds it popups up a dialog and hangs FF until you click dismiss.  This isn't possible in a headless environment...  I'm not sure if this totally resolves the issue or just lets you get to the next one but this might help:

          'user_pref("dom.max_script_run_time", 0);'

**Comment by adhamhf** [comment]
actually, I think that did solve it.  My shrinkwrap file was preventing me from getting the change though.  I'm going to test more and maybe I'll be able to send up a PR.  It seems like sometimes our CI is under load and this causes the JS to run slow enough in FF to kick this dialog in.  I have noticed this more when using xvfb-run than I have with xvfb directly, but I have no empirical data.

**Comment by adhamhf** [comment]
@johanneswuerbach  PR https://github.com/testem/testem/pull/984 will fix this.
