### ISSUE TITLE
Custom launchers hang on big output

### ISSUE THREAD

**Issue by chrmod** [testem/testem#958]
As launcher processes as created using `chilld_process.exec` (https://github.com/testem/testem/blob/master/lib/process-ctl.js#L89) their output is limited to maxBuffer size, which is 200kb (https://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback).
This results in runners waiting for all tests results which will never come in effect testem hangs.

There are two potential solution for the issue:
* increasing default `maxBuffer` for launcher process
* using `spawn` instead of `exec`

Have tested both solutions with success. Going to submit the later one as PR.

**Comment by johanneswuerbach** [comment]
You can already use `spawn` today by specifying `exe` and `args` instead of a `cmd` in your launcher config.

Example: https://github.com/testem/testem/blob/760e5c8b1d892c357bcce321cbd24b8ab899c4a8/examples/saucelabs/testem.json#L20-L21

**Comment by chrmod** [comment]
@johanneswuerbach are you willing to accept the PR or rather deprecate `command` option?

**Comment by johanneswuerbach** [comment]
I would definitely like to replace of usages of exec with spawn, but always wondered about the args parsing and all possible edges related to that when converting `cmd` => `exe` + `args`.

If that is figured out, the change should be easy.
