### ISSUE TITLE
maxDepth is reached for trivial objects

### ISSUE THREAD

**Issue by jzaefferer** [testem/testem#962]
Using testem@1.10.4, I'm running into an issue that #811 was supposed to fix. There, maxDepth in decycle.js was increased from 4 to 5, which seems not enough for a trivial QUnit `deepEqual` comparison. In my test, I'm using ember-cli, which integrates testem. This is the test itself:

```
import { moduleForModel, test } from 'ember-qunit';

moduleForModel('max-depth', 'Unit | Model | max depth');

test('it exists', function(assert) {
  assert.deepEqual({
    a: 1,
    b: {
      c: [2, 3, 4]
    }
  }, {});
});
```

Expected (output running QUnit in browser):
![...](http://bassistance.de/i/515589.png)

Actual (output running same testsuite via ember-cli/testem):

```
13) [PhantomJS 2.1] Unit | Model | max depth: it exists

     expected: {}
       actual: { a: 'Max depth.', b: 'Max depth.' }

     http://localhost:7357/assets/tests.js:315:21
     wrapper@http://localhost:7357/assets/test-support.js:6634:34
     runTest@http://localhost:7357/assets/test-support.js:2779:32
     run@http://localhost:7357/assets/test-support.js:2764:11
     http://localhost:7357/assets/test-support.js:2906:14
     process@http://localhost:7357/assets/test-support.js:2565:24
     begin@http://localhost:7357/assets/test-support.js:2547:9
     http://localhost:7357/assets/test-support.js:2607:9
```

I've looked a bit at the code, but I can't say that I quite understand what happens there :/

As a bonus, this seems to be the equivalent module in QUnit itself, which also has a maxDepth option: https://github.com/jquery/qunit/blob/master/src/dump.js

Let me know if you need more information to reproduce this, I could attach my ember-cli test project. If there's a template for something only using testem, let me know, and I can use that instead.

**Comment by jzaefferer** [comment]
@johanneswuerbach any thoughts on this? Is there a history here besides the issue I linked to that I should be aware of? I can try to provide a PR, any guidance would help.

**Comment by johanneswuerbach** [comment]
I think the best approach would be a configurable max depth. The current settings was choosen based on some test with a larg-ish test suite and IE 8. Modern browsers shouldn't have any problems with serializing/deserialzing larger objects, but mobile still might so a configurable setting would should both worlds happy

**Comment by jzaefferer** [comment]
I see. Though that sounds like it won't address the underlying issue: Its purging top-level properties! They're not beyond the current max depth, they're well below. Any idea what's causing my harmless object to be mistaken to be several levels deep?

**Comment by johanneswuerbach** [comment]
I'm currently only on my mobile, but I guess your object is just a part of a larger object send from the testem client to the server and so 5 levels doesn't mean 5 levels of your objects. Another possible solution might be to no evaluate the testem boilerplate and just cut user provided objects.

**Comment by jzaefferer** [comment]
> Another possible solution might be to no evaluate the testem boilerplate and just cut user provided objects.

That sounds like a better approach. Last time I looked at the code, I had no clue how to do that though.

**Comment by oniofchaos** [comment]
Experiencing the same on testem@1.13.0

**Comment by netes** [comment]
Same here.

**Comment by lolmaus** [comment]
Is [this](https://github.com/emberjs/ember.js/issues/15033#issuecomment-289835635) the same problem or should I open a new one?

**Comment by johanneswuerbach** [comment]
Doesn't appear to be related, but more like this check is breaking your app https://github.com/testem/testem/blob/master/public/testem/decycle.js#L67

Maybe adding a `&& 'nodeType' in value` before `&& typeof value.nodeType === 'number'` could fix this?
