### ISSUE TITLE
Hooks and build tool daemons

### ISSUE THREAD

**Issue by rupurt** [testem/testem#980]
Howdy,

Our test suite has grown in size and we're starting to run into performance issues when using `testem` with `Webpack`. Currently we're watching our src directories via `testem` and running the `Webpack` build step in a `before_tests` hook.

```json
{
  "before_tests": "webpack --config webpack.test.config.js",
  "on_exit": "rm tests/tmp/*",
  "framework": "mocha+chai",
  "test_page": "tests/index.html",
  "launch_in_dev": [
    "Chrome"
  ],
  "launch_in_ci": [
    "Chrome"
  ],
  "src_files": [
    "./app/bundles/**/*.js",
    "./app/bundles/**/*.jsx",
    "./tests/bundles/**/*.js",
    "./tests/bundles/**/*.jsx",
    "./tests/lib/**/*.js",
    "./tests/lib/**/*.jsx",
    "./tests/helpers/**/*.js"
  ],
  "serve_files": [
    "./tests/tmp/tests-bundle.js"
  ],
  "routes": {
    "/tests/index.html": "tests/index.html.mustache"
  }
}
```

This is suboptimal because it takes ~30s to complete a build from scratch and < 1s to complete a partial build when using `Webpack` in watch mode. I changed the `testem` config to use the `on_start` hook instead and it seems to mostly work. However it breaks `testem` command input (i.e. q to quit, p to pause, ENTER to run tests) and ci mode.

```json
{
  "on_start": "webpack --config webpack.test.config.js --watch",
  "on_exit": "rm tests/tmp/*",

   // more config...

  "src_files": [
    "./tests/tmp/tests-bundle.js"
  ],
  "serve_files": [
    "./tests/tmp/vendor-bundle.js",
    "./tests/tmp/uikit-bundle.js",
    "./tests/tmp/tests-bundle.js"
  ]
}
```

Do you have any suggestions on how to make this workflow work or where I should look to modify to submit a PR?

Cheers

**Comment by rupurt** [comment]
I managed to figure it out. The key was to use a custom `wait_for_text` in the `on_start` hook. e.g.

```json
{
    "on_start": {
       "command": "rm tests/tmp/* & webpack --config webpack.test.config.js --watch",
       "wait_for_text": "[built]",
       "wait_for_text_timeout": 300000
     },
     "on_exit": "rm tests/tmp/*"
}
```

**Comment by pwang2** [comment]
I have the same needed to use testem with webpack-dev-server. It turns out your workaround is not working.  pressing q still hanging there. Here I am using & start a backend process.

on_start: webpack-dev-server --inline --config webpack.config.js --port 8080 & echo $! > testem_webpack_dev_server.pid
on_exit: cat testem_webpack_dev_server.pid | xargs kill -9 && rm testem_webpack_dev_server.pid

This should be even more performed than webpack -w and we got the livereload for free.  could you let me know if I miss anything?
