### ISSUE TITLE
Run test page in https environment

### ISSUE THREAD

**Issue by ikondrat** [testem/testem#992]
Hi as I havn't found answer for my question in issues or description I will try to find it as issue.

I assumed that it is possible to use https for test page, but then I set **url: 'https://host:port'** test doesn't run in Development Mode(with PhantomJs or any other launcher)

Is it known issue or limitation? Thanks for answer

**Comment by johanneswuerbach** [comment]
There is an undocumented way to serve testem via https by providing a key or pfx https://github.com/testem/testem/pull/498

**Comment by ikondrat** [comment]
@johanneswuerbach Thanks a lot i will try to use it
